/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas.Jpanel;
import Modelo.Habitacion;
import Controladores.ControllerHabitacion;
import Controladores.ControllerServicios;
import Modelo.RoomServices;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author nicol
 */
public class AgregarServicioRecepGUI extends javax.swing.JPanel {

    int cantidadProductos;
    ArrayList<jPserviciosRecepcionista> aux = new ArrayList<>();
 
    /** Creates new form AgregarServicioRecepGUI */
    public AgregarServicioRecepGUI() {
        initComponents();
        AgregarListaHabitaciones();
        ServciosAgregarCantidad();
        listaServiciosAñadidos();
    }

    
    
    private void AgregarListaHabitaciones(){
        
        //MOSTRAR HABITACIÓN POR SU TIPO 
         ArrayList<Habitacion> listado = new ArrayList<>();
       ControllerHabitacion controlador = new ControllerHabitacion();
       listado = ControllerHabitacion.listadoHabitacionesOcupadas();
       
       cantidadProductos = listado.size();
       
       for(int i=0; i<listado.size(); i++){
        jPnumeroHabitacion habi = new jPnumeroHabitacion(listado.get(i).getId_habitacion());           
        jPcontenido.add(habi);       
        jPcontenido.revalidate();
        jPcontenido.repaint();
       }   
    }
    
    
    private ArrayList<RoomServices> HacerListaServ(){
        
        ArrayList<RoomServices> listado = new ArrayList<>();
        ControllerServicios controlador = new ControllerServicios();
        listado = ControllerServicios.desplegarServicios();
        
        return listado;
    }
    
    private ArrayList<RoomServices> ServciosAgregarCantidad(){
        
        //AGREGAR CANTIDAD A SERVICIOS POR AÑADIR    
      ArrayList<jPserviciosRecepcionista> aux1 = new ArrayList<>();
        
       ArrayList<RoomServices> listado = new ArrayList<>();
       
       listado = HacerListaServ();
       
       for(int i=0; i<listado.size(); i++){
                 jPserviciosRecepcionista ser = new jPserviciosRecepcionista(
                         listado.get(i).getNombrePro(),
                         listado.get(i).getPrecio(),
                         listado.get(i).getCantidad()
                 );
                 aux.add(ser);
                 jPingresoCantidad.add(ser);
                 
                 jPingresoCantidad.revalidate();
                 jPingresoCantidad.repaint();
       } 
        System.out.println(aux.size() + aux.get(2).getNombre());
       return listado;
    }
    
     private void listaServiciosAñadidos(){
        
        //AGREGAR CANTIDAD A SERVICIOS POR AÑADIR    
        
       //jCservicios.add();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jPcontenido = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPlistaServicios = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPingresoCantidad = new javax.swing.JPanel();
        jCtipoHabitacion = new javax.swing.JComboBox();
        jBañadir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jBcancelar = new javax.swing.JButton();
        jBguardar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane4.setBorder(null);
        jScrollPane4.setHorizontalScrollBar(null);

        jPcontenido.setBackground(new java.awt.Color(255, 255, 255));
        jPcontenido.setLayout(new java.awt.GridLayout(0, 3, 0, 1));
        jScrollPane4.setViewportView(jPcontenido);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 98, 530, 370));

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBar(null);

        jPlistaServicios.setBackground(new java.awt.Color(255, 255, 255));
        jPlistaServicios.setLayout(new java.awt.GridLayout(0, 1, 0, 1));
        jScrollPane3.setViewportView(jPlistaServicios);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, 240, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/marcoServiciosLista.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 92, -1, -1));

        jScrollPane5.setBorder(null);
        jScrollPane5.setHorizontalScrollBar(null);

        jPingresoCantidad.setBackground(new java.awt.Color(255, 255, 255));
        jPingresoCantidad.setLayout(new java.awt.GridLayout(0, 1, 0, 1));
        jScrollPane5.setViewportView(jPingresoCantidad);

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 114, 200, 90));

        jCtipoHabitacion.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jCtipoHabitacion.setForeground(new java.awt.Color(204, 204, 204));
        jCtipoHabitacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Simple" }));
        jCtipoHabitacion.setBorder(null);
        jCtipoHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCtipoHabitacionActionPerformed(evt);
            }
        });
        add(jCtipoHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 37, 122, 20));

        jBañadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonAñadir.png"))); // NOI18N
        jBañadir.setBorder(null);
        jBañadir.setContentAreaFilled(false);
        jBañadir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBañadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBañadirMouseClicked(evt);
            }
        });
        jBañadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBañadirActionPerformed(evt);
            }
        });
        add(jBañadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(855, 203, -1, -1));

        jLabel3.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(165, 165, 165));
        jLabel3.setText("Habitaciones :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 37, -1, -1));

        jBcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar-sinSeleccion.png"))); // NOI18N
        jBcancelar.setContentAreaFilled(false);
        jBcancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBcancelar.setInheritsPopupMenu(true);
        jBcancelar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar-seleccionado.png"))); // NOI18N
        jBcancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBcancelarMouseClicked(evt);
            }
        });
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });
        add(jBcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 441, 130, 50));

        jBguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar-SinSele.png"))); // NOI18N
        jBguardar.setBorder(null);
        jBguardar.setContentAreaFilled(false);
        jBguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBguardar.setInheritsPopupMenu(true);
        jBguardar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuardarSele.png"))); // NOI18N
        jBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarActionPerformed(evt);
            }
        });
        add(jBguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(826, 441, 140, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ListaServiciosAgregar.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 45, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ListaServicios2.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 258, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jCtipoHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCtipoHabitacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCtipoHabitacionActionPerformed

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jBguardarActionPerformed

    private void jBañadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBañadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBañadirActionPerformed

    
   
    
    private void jBañadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBañadirMouseClicked
        
        
        int posicion = -1;
         for(int i=0; i<aux.size(); i++)
         {
             if(aux.get(i).getEstado() == true);
             {
                 posicion = i;
             }
         }
         
       
           System.out.print(aux.get(posicion).getEstado());
         
           aux.get(posicion).setEstado(false);
      
         
         if(posicion != -1)
         {
            jPserviciosRecepcionista2 añadido = new jPserviciosRecepcionista2(
                     aux.get(posicion).getNombre(),
                     aux.get(posicion).getPrecio(),
                     1);
            
              jPlistaServicios.add(añadido);       
              jPlistaServicios.revalidate();
              jPlistaServicios.repaint();
         }
        
      
       
       
       
    
    }//GEN-LAST:event_jBañadirMouseClicked

    private void jBcancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBcancelarMouseClicked
        jPlistaServicios.removeAll();
    }//GEN-LAST:event_jBcancelarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBañadir;
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBguardar;
    private javax.swing.JComboBox jCtipoHabitacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPcontenido;
    private javax.swing.JPanel jPingresoCantidad;
    private javax.swing.JPanel jPlistaServicios;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables

}
