/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas.Jpanel;

/**
 *
 * @author nicol
 */
public class AgregarServicioRecepGUI extends javax.swing.JPanel {

    /** Creates new form AgregarServicioRecepGUI */
    public AgregarServicioRecepGUI() {
        initComponents();
        AgregarListaHabitaciones();
        ListaServcios();
    }

    private void AgregarListaHabitaciones(){
        
        //MOSTRAR HABITACIÓN POR SU TIPO
       jPnumeroHabitacion habi = new jPnumeroHabitacion();
       for(int i=0;i<10;i++){           
        jPcontenido.add(habi);       
        jPcontenido.revalidate();
        jPcontenido.repaint();
       }   
    }
    
    private void ListaServcios(){
        //AGREGAR LISTA SERVICIOS A JCOMBOBOX
       //jCservicios.add();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPcontenido = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCtipoHabitacion = new javax.swing.JComboBox();
        jCservicios = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBcancelar = new javax.swing.JButton();
        jBguardar = new javax.swing.JButton();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Decker", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(165, 165, 165));
        jLabel4.setText("Servicios");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 127, -1, -1));

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBar(null);

        jPcontenido.setBackground(new java.awt.Color(255, 255, 255));
        jPcontenido.setLayout(new java.awt.GridLayout(0, 3, 0, 1));
        jScrollPane3.setViewportView(jPcontenido);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 90, 550, 400));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/marcoServiciosLista.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 78, -1, -1));

        jCtipoHabitacion.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jCtipoHabitacion.setForeground(new java.awt.Color(204, 204, 204));
        jCtipoHabitacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Simple" }));
        jCtipoHabitacion.setBorder(null);
        jCtipoHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCtipoHabitacionActionPerformed(evt);
            }
        });
        add(jCtipoHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 37, 122, 20));

        jCservicios.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jCservicios.setForeground(new java.awt.Color(204, 204, 204));
        jCservicios.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Simple" }));
        jCservicios.setBorder(null);
        jCservicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCserviciosActionPerformed(evt);
            }
        });
        add(jCservicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 127, 122, 20));

        jLabel3.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(165, 165, 165));
        jLabel3.setText("Habitaciones :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 37, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MarcoServicioAgregar.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 78, -1, -1));

        jBcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar-sinSeleccion.png"))); // NOI18N
        jBcancelar.setContentAreaFilled(false);
        jBcancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBcancelar.setInheritsPopupMenu(true);
        jBcancelar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar-seleccionado.png"))); // NOI18N
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });
        add(jBcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 350, 130, 50));

        jBguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar-SinSele.png"))); // NOI18N
        jBguardar.setBorder(null);
        jBguardar.setContentAreaFilled(false);
        jBguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBguardar.setInheritsPopupMenu(true);
        jBguardar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuardarSele.png"))); // NOI18N
        jBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarActionPerformed(evt);
            }
        });
        add(jBguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(842, 350, 140, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jCtipoHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCtipoHabitacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCtipoHabitacionActionPerformed

    private void jCserviciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCserviciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCserviciosActionPerformed

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jBguardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBguardar;
    private javax.swing.JComboBox jCservicios;
    private javax.swing.JComboBox jCtipoHabitacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPcontenido;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

}
