/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Jpanel;

import java.util.ArrayList;
import Controladores.ControladorCliente;
import Modelo.Cliente;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import Vistas.Jframe.Clientes;
import Vistas.Jpanel.jPcliente;
import Vistas.Jpanel.jPmensaje;

/**
 *
 * @author nicol
 */
public class ClienteListaGUI extends javax.swing.JPanel {
    
    ControladorCliente controladorCliente =  new ControladorCliente();
    Clientes panel_prin;
    
    
    private ArrayList<jPcliente> clientes;
    /**
     * Creates new form ClienteListaGUI
     */
    public ClienteListaGUI(){}
    
    public ClienteListaGUI(Clientes cli) {
        clientes = new ArrayList<>();
        this.panel_prin = cli;
        initComponents();
        CargarLista(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPmensajes = new javax.swing.JPanel();
        jTbuscador = new javax.swing.JTextField();
        jBbuscar = new javax.swing.JButton();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ContornoHabitacion.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 84, -1, -1));

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBar(null);

        jPmensajes.setBackground(new java.awt.Color(255, 255, 255));
        jPmensajes.setLayout(new java.awt.GridLayout(0, 3, 0, 1));
        jScrollPane3.setViewportView(jPmensajes);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 90, 710, 340));

        jTbuscador.setFont(new java.awt.Font("Decker", 0, 15)); // NOI18N
        jTbuscador.setForeground(new java.awt.Color(191, 191, 191));
        jTbuscador.setText("Buscar cliente por ID");
        jTbuscador.setBorder(null);
        jTbuscador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbuscadorMouseClicked(evt);
            }
        });
        jTbuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTbuscadorActionPerformed(evt);
            }
        });
        jTbuscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTbuscadorKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTbuscadorKeyPressed(evt);
            }
        });
        add(jTbuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 47, 174, 19));

        jBbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar-azul.png"))); // NOI18N
        jBbuscar.setBorder(null);
        jBbuscar.setBorderPainted(false);
        jBbuscar.setContentAreaFilled(false);
        jBbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBbuscarMouseClicked(evt);
            }
        });
        add(jBbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 44, 24, 24));
    }// </editor-fold>//GEN-END:initComponents

    private void jTbuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTbuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTbuscadorActionPerformed

    private void jBbuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBbuscarMouseClicked
        if (jTbuscador.getText().isEmpty() || jTbuscador.getText() == "") {
                CargarLista(0);
            }else{
        CargarLista(Integer.parseInt(jTbuscador.getText().trim()));
        }
    }//GEN-LAST:event_jBbuscarMouseClicked

    private void jTbuscadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbuscadorMouseClicked
         if(jTbuscador.getText().equalsIgnoreCase("Buscar cliente por ID")){
            jTbuscador.setText("");
        } else{}
    }//GEN-LAST:event_jTbuscadorMouseClicked

    private void jTbuscadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTbuscadorKeyTyped
      
    }//GEN-LAST:event_jTbuscadorKeyTyped

    private void jTbuscadorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTbuscadorKeyPressed
        int key = evt.getKeyCode();
        if(key == KeyEvent.VK_ENTER){
            if (jTbuscador.getText().isEmpty() || jTbuscador.getText() == "") {
                CargarLista(0);
            }else{
         CargarLista(Integer.parseInt(jTbuscador.getText()));
            }
        }
    }//GEN-LAST:event_jTbuscadorKeyPressed

        
    private void cleanLista(){
        
        clientes.clear();
        jPmensajes.removeAll();
        jPmensajes.revalidate();
        jPmensajes.repaint();
        
        
    }
     public void CargarLista(int id){
       
        ArrayList<Cliente> listadoCli = new ArrayList<>();
            listadoCli = controladorCliente.listClients(0);

            jPmensajes.removeAll();
            for (int i = 0; i < listadoCli.size(); i++) {
                jPcliente jpcli = new 
                    jPcliente(listadoCli.get(i), panel_prin);
                if(id==0 || jTbuscador.getText()==""){
                    clientes.add(jpcli);
                }else{
                    if (id==listadoCli.get(i).getID()) {
                        cleanLista();
                        clientes.add(jpcli);
                        break;
                    } else {
                        cleanLista();
                       jPmensajes.add(
                                new jPmensaje
                                         ("Tu búsqueda no tuvo resultados!"));
                    }
                }
                

            
       }
        
        //LA LISTA ES CARGADA EN UN JPANEL 
        for(int i=0;i<clientes.size();i++){          
        jPmensajes.add(clientes.get(i));
        jPmensajes.revalidate();
        jPmensajes.repaint();}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBbuscar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPmensajes;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTbuscador;
    // End of variables declaration//GEN-END:variables
}
