/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Jpanel;

import Modelo.Cliente;
import Modelo.ClientDAO;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author nicol
 */
public class ClientesAgregarModificarGUI extends javax.swing.JPanel {
    
    
    ClientDAO clientDAO = new ClientDAO();
    

    /**
     * Creates new form ClientesAgregarModificarGUI
     */
    public ClientesAgregarModificarGUI() {
        
        initComponents();
        
        
    }

    public void llenarValores(Cliente cliente) {

        String Cedula = String.valueOf(cliente.getID());
        jTCedula.setText(Cedula);
        jTnombre.setText(cliente.getNombre() + " " + cliente.getApellido());
        jTcorreo.setText(cliente.getCorreo());
        jTtelefono.setText(cliente.getTelefono());
        jTdireccion.setText(cliente.getDireccion());
    }
    
    public Cliente getData() {
        int cedula, telefono;
        String nombre, apellido, correo, direccion;
       
       // Se extrae la info de los campos y se guardan en una var(gClient) que cambiará de valor cada vez 
       // que se oprima "Guardar", luego en añadir se enviará toda esta info a la BD
    
        Cliente gClient = new Cliente();
       //Extraer el nombre y apellido de jTnombre
       String[] names = jTnombre.getText().split(" ");
       gClient.setNombre(names[0]);
       if(names.length>1){
           gClient.setApellido(names[1]);
        } else {
           apellido= "";
       }
       
       gClient.setID(Integer.parseInt(jTCedula.getText().trim())) ;
       gClient.setCorreo(jTcorreo.getText().trim());
       gClient.setDireccion(jTdireccion.getText().trim());
       gClient.setTelefono(jTtelefono.getText().trim());
       
       return gClient;
        
    }
    
    
    public void saveData() {
       try{
           Cliente cliente=getData();
           if(verifyData(cliente)){
                clientDAO.addClient(cliente);
                System.out.println("Cliente agregado!");
            }
       }
       catch(Exception e){}
    }
    
    public boolean verifyData(Cliente gClient) {
       int cedula, telefono;
       String nombre, apellido, correo, direccion;
       String regexEmail = "^[\\w!#$%&'*+/=?`{|}~^-]+(?:\\.[\\w!#$%&'*+/=?`{|}~^-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$";
 
        Pattern pattern = Pattern.compile(regexEmail);
        correo="";
        Matcher matcher = pattern.matcher(correo);
       try{
            cedula=gClient.getID();
            try{
                telefono=Integer.parseInt(gClient.getTelefono());
            }
            catch(Exception e)
            {
                // TODO :: Add the report of an invalid field on a notification
                telefono=999101999;
                System.out.println("Error // Phone:" + e.toString());
            };

            nombre=gClient.getNombre();
            apellido=gClient.getApellido();
            Matcher matcherEmail = pattern.matcher(correo);
            try{
                if(matcherEmail.matches()) {
                correo=gClient.getCorreo();
                }
                
              
            }
            catch(Exception e){}
            direccion=gClient.getDireccion();
            
       } catch(Exception e){
           System.out.println("Error: " + e.toString());
           return false;
       }
        
       
       return true;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBguardar = new javax.swing.JButton();
        jBcancelar = new javax.swing.JButton();
        jTdireccion = new javax.swing.JTextField();
        jTnombre = new javax.swing.JTextField();
        jTCedula = new javax.swing.JTextField();
        jTcorreo = new javax.swing.JTextField();
        jTtelefono = new javax.swing.JTextField();
        jLfondo = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar-blanco.png"))); // NOI18N
        jBguardar.setBorder(null);
        jBguardar.setBorderPainted(false);
        jBguardar.setContentAreaFilled(false);
        jBguardar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar-seleccionado.png"))); // NOI18N
        jBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarActionPerformed(evt);
            }
        });
        add(jBguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, -1, -1));

        jBcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar-sinSeleccion.png"))); // NOI18N
        jBcancelar.setContentAreaFilled(false);
        jBcancelar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar-seleccionado.png"))); // NOI18N
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });
        add(jBcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 130, 50));

        jTdireccion.setBackground(new java.awt.Color(241, 242, 246));
        jTdireccion.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jTdireccion.setForeground(new java.awt.Color(153, 153, 153));
        jTdireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        add(jTdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 190, 30));

        jTnombre.setBackground(new java.awt.Color(241, 242, 246));
        jTnombre.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jTnombre.setForeground(new java.awt.Color(153, 153, 153));
        jTnombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        add(jTnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 190, 30));

        jTCedula.setBackground(new java.awt.Color(241, 242, 246));
        jTCedula.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jTCedula.setForeground(new java.awt.Color(153, 153, 153));
        jTCedula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCedulaActionPerformed(evt);
            }
        });
        add(jTCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 190, 30));

        jTcorreo.setBackground(new java.awt.Color(241, 242, 246));
        jTcorreo.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jTcorreo.setForeground(new java.awt.Color(153, 153, 153));
        jTcorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        add(jTcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 190, 30));

        jTtelefono.setBackground(new java.awt.Color(241, 242, 246));
        jTtelefono.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jTtelefono.setForeground(new java.awt.Color(153, 153, 153));
        jTtelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTtelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTtelefonoActionPerformed(evt);
            }
        });
        add(jTtelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 190, 30));

        jLfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo-cli.png"))); // NOI18N
        jLfondo.setPreferredSize(new java.awt.Dimension(739, 429));
        add(jLfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarActionPerformed
        saveData(); // Se ejecuta, se envia la data a la BD 
        jBcancelarActionPerformed(evt);
    }//GEN-LAST:event_jBguardarActionPerformed

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
        jTCedula.setText("");
        jTnombre.setText("");
        jTcorreo.setText("");
        jTtelefono.setText("");
        jTdireccion.setText("");
    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jTCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCedulaActionPerformed

    private void jTtelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTtelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTtelefonoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBguardar;
    private javax.swing.JLabel jLfondo;
    private javax.swing.JTextField jTCedula;
    private javax.swing.JTextField jTcorreo;
    private javax.swing.JTextField jTdireccion;
    private javax.swing.JTextField jTnombre;
    private javax.swing.JTextField jTtelefono;
    // End of variables declaration//GEN-END:variables
}
