/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Jpanel;

import java.util.ArrayList;
import Controladores.ControladorEmpleado;
import Modelo.Empleado;
import Vistas.Jframe.Empleados;
import javax.swing.JOptionPane;

/**
 *
 * @author nicol
 */
public class EmpleadoPanelListar extends javax.swing.JPanel {
    
    ControladorEmpleado ControladorEmp =  new ControladorEmpleado();
    Empleados panel_prin;
    private ArrayList<jPempleado> empleados;
    /**
     * Creates new form EmpleadoListaGUI
     */
    public EmpleadoPanelListar(Empleados s) {
        this.panel_prin = s;
        empleados = new ArrayList<>();
        initComponents();
        CargarLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jPmensajes = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTbuscador = new javax.swing.JTextField();
        jBbuscar = new javax.swing.JButton();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBar(null);

        jPmensajes.setBackground(new java.awt.Color(255, 255, 255));
        jPmensajes.setLayout(new java.awt.GridLayout(0, 3, 0, 1));
        jScrollPane3.setViewportView(jPmensajes);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 90, 710, 340));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ContornoHabitacion.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 84, -1, -1));

        jTbuscador.setFont(new java.awt.Font("Decker", 0, 15)); // NOI18N
        jTbuscador.setForeground(new java.awt.Color(191, 191, 191));
        jTbuscador.setText("Buscar empleado por ID");
        jTbuscador.setBorder(null);
        jTbuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTbuscadorActionPerformed(evt);
            }
        });
        add(jTbuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 47, 174, 19));

        jBbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar-azul.png"))); // NOI18N
        jBbuscar.setBorder(null);
        jBbuscar.setBorderPainted(false);
        jBbuscar.setContentAreaFilled(false);
        jBbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jBbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 44, 24, 24));
    }// </editor-fold>//GEN-END:initComponents

    private void jTbuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTbuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTbuscadorActionPerformed

    public void CargarLista(){
        
        //TODA LOS EMPLEADOS SON AGREGADOS AL JPANEL 
        //EN DONDE SE MUESTRA LOS DATOS PRINCIPALES DE LOS EMPLEADOS
        
        ArrayList<Empleado> listadoEmp = new ArrayList<>();
        listadoEmp = ControladorEmp.listadoEmpleado(0);
        
        
        jPmensajes.removeAll();
        for (int i=0;i<listadoEmp.size();i++){
        jPempleado jp = new jPempleado(listadoEmp.get(i), panel_prin);
        empleados.add(jp);
          
       }
        for(int i=0;i<empleados.size();i++){          
        jPmensajes.add(empleados.get(i));
        
        jPmensajes.revalidate();
        jPmensajes.repaint();}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBbuscar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPmensajes;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTbuscador;
    // End of variables declaration//GEN-END:variables
}
