/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Jpanel;

import Modelo.Empleado;

/**
 *
 * @author nicol
 */
public class EmpleadoAgregarModificarGUI extends javax.swing.JPanel {

    /**
     * Creates new form EmpleadoAgregarModificarGUI
     */
    public EmpleadoAgregarModificarGUI() {
        initComponents();
    }

    
    public void llenarValores(Empleado datos){
        
        String Cedula = String.valueOf(datos.getID());
        jTcedula.setText(Cedula);
        jTnombre.setText(datos.getNombre() + " " + datos.getApellido());
        jTcargo.setText(datos.getCargo());
        jTcorreo.setText(datos.getCorreo());
        jTtelefono.setText(datos.getTelefono());
        jTdireccion.setText(datos.getDireccion());
        if (datos.getEstado() == true)
        {
            jCestado.setSelectedItem("Activo");
        }else {
            jCestado.setSelectedItem("Inactivo");
        }
                    
       
        
        
        
        
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBcancelar = new javax.swing.JButton();
        jBguardar = new javax.swing.JButton();
        jTcedula = new javax.swing.JTextField();
        jTnombre = new javax.swing.JTextField();
        jTtelefono = new javax.swing.JTextField();
        jTdireccion = new javax.swing.JTextField();
        jTcargo = new javax.swing.JTextField();
        jTsalario = new javax.swing.JTextField();
        jTcorreo = new javax.swing.JTextField();
        jCestado = new javax.swing.JComboBox<>();
        jLfondo = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar-sinSeleccion.png"))); // NOI18N
        jBcancelar.setContentAreaFilled(false);
        jBcancelar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar-seleccionado.png"))); // NOI18N
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });
        add(jBcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 130, 50));

        jBguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar-blanco.png"))); // NOI18N
        jBguardar.setBorder(null);
        jBguardar.setBorderPainted(false);
        jBguardar.setContentAreaFilled(false);
        jBguardar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar-seleccionado.png"))); // NOI18N
        jBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarActionPerformed(evt);
            }
        });
        add(jBguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, -1, -1));

        jTcedula.setBackground(new java.awt.Color(241, 242, 246));
        jTcedula.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jTcedula.setForeground(new java.awt.Color(153, 153, 153));
        jTcedula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        add(jTcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 190, 30));

        jTnombre.setBackground(new java.awt.Color(241, 242, 246));
        jTnombre.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jTnombre.setForeground(new java.awt.Color(153, 153, 153));
        jTnombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        add(jTnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 190, 30));

        jTtelefono.setBackground(new java.awt.Color(241, 242, 246));
        jTtelefono.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jTtelefono.setForeground(new java.awt.Color(153, 153, 153));
        jTtelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        add(jTtelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 190, 30));

        jTdireccion.setBackground(new java.awt.Color(241, 242, 246));
        jTdireccion.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jTdireccion.setForeground(new java.awt.Color(153, 153, 153));
        jTdireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        add(jTdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 190, 30));

        jTcargo.setBackground(new java.awt.Color(241, 242, 246));
        jTcargo.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jTcargo.setForeground(new java.awt.Color(153, 153, 153));
        jTcargo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        add(jTcargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 190, 30));

        jTsalario.setBackground(new java.awt.Color(241, 242, 246));
        jTsalario.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jTsalario.setForeground(new java.awt.Color(153, 153, 153));
        jTsalario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        add(jTsalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 190, 30));

        jTcorreo.setBackground(new java.awt.Color(241, 242, 246));
        jTcorreo.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jTcorreo.setForeground(new java.awt.Color(153, 153, 153));
        jTcorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcorreoActionPerformed(evt);
            }
        });
        add(jTcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 190, 30));

        jCestado.setBackground(new java.awt.Color(241, 242, 246));
        jCestado.setForeground(new java.awt.Color(153, 153, 153));
        jCestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2" }));
        add(jCestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 190, 30));

        jLfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo-emp.png"))); // NOI18N
        jLfondo.setPreferredSize(new java.awt.Dimension(739, 429));
        add(jLfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jBguardarActionPerformed

    private void jTcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTcorreoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBguardar;
    private javax.swing.JComboBox<String> jCestado;
    private javax.swing.JLabel jLfondo;
    private javax.swing.JTextField jTcargo;
    private javax.swing.JTextField jTcedula;
    private javax.swing.JTextField jTcorreo;
    private javax.swing.JTextField jTdireccion;
    private javax.swing.JTextField jTnombre;
    private javax.swing.JTextField jTsalario;
    private javax.swing.JTextField jTtelefono;
    // End of variables declaration//GEN-END:variables
}
