/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Jpanel;

import Modelo.Habitacion;
import Vistas.Jframe.Habitaciones;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Set;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nicol
 */
public class HabitacionListaGUI extends javax.swing.JPanel {

    // private ArrayList<jPhabitacion> jphabitaciones;
    //private ArrayList <Habitaciones1> hab;
    /**
     * Creates new form HabitacionEliminarGUI
     */
    Habitaciones frame_habitaciones;
    jPhabitacion jp;

    public HabitacionListaGUI(Habitaciones frame_habitaciones) {
        //jphabitaciones = new ArrayList<>();
        //hab = new ArrayList<>();
        this.frame_habitaciones = frame_habitaciones;
        //frame_habitaciones = new Habitaciones();

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTbuscador = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPmensajes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBbuscar = new javax.swing.JButton();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTbuscador.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jTbuscador.setForeground(new java.awt.Color(204, 204, 204));
        jTbuscador.setText("Buscador...");
        jTbuscador.setBorder(null);
        jTbuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTbuscadorActionPerformed(evt);
            }
        });
        add(jTbuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 360, 20));

        jScrollPane3.setHorizontalScrollBar(null);

        jPmensajes.setBackground(new java.awt.Color(255, 255, 255));
        jPmensajes.setLayout(new java.awt.GridLayout(0, 3, 0, 1));
        jScrollPane3.setViewportView(jPmensajes);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 730, 400));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscador.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jBbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa.png"))); // NOI18N
        jBbuscar.setBorder(null);
        jBbuscar.setBorderPainted(false);
        jBbuscar.setContentAreaFilled(false);
        jBbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jBbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 40, 30));
    }// </editor-fold>//GEN-END:initComponents

    public void CargarLista
        (ArrayList<Habitacion> lista_habitacion, String validador) {

        //TODA LAS HABITACIONES SON AGREGADAS AL JPANEL 
        //EN DONDE SE MUESTRA LOS DATOS PRINCIPALES DE LAS HABITACIONES
        jPmensajes.removeAll();
        ArrayList<jPhabitacion> jphabitaciones = new ArrayList<>();

        for (int i = 0; i < lista_habitacion.size(); i++) {

            int id_hab = lista_habitacion.get(i).getId_habitacion();
            String tipo_hab = lista_habitacion.get(i).getTipo_habitacion();
            String piso = lista_habitacion.get(i).getPiso();
            int cantidad_personas = lista_habitacion.get(i)
                    .getCantidadPersonas();
            int precio_hab = lista_habitacion.get(i).getPrecio_hab();
            boolean estado_hab = lista_habitacion.get(i).getEstado();

            jp = new jPhabitacion(id_hab, tipo_hab, piso, cantidad_personas, 
                    precio_hab, estado_hab, frame_habitaciones);
            jp.setValidadorPanel(validador);
            jphabitaciones.add(jp);

        }

        for (int i = 0; i < jphabitaciones.size(); i++) {
            jPmensajes.add(jphabitaciones.get(i));

            jPmensajes.revalidate();
            jPmensajes.repaint();
        }
    }

    public JPanel getjPmensajes() {
        return jPmensajes;
    }

    public void llenarFormulario(Habitacion habitacion) {

        int id_hab = habitacion.getId_habitacion();
        String tipo_hab = habitacion.getTipo_habitacion(); //combobox
        String piso = habitacion.getPiso();
        int cantidad_personas = habitacion.getCantidadPersonas();
        int precio_hab = habitacion.getPrecio_hab();
        int num_camas = habitacion.getNum_camas(); //combobox

        frame_habitaciones.getPanelAgregar().getjTnumeroHabitacion()
                .setText("" + id_hab);
        frame_habitaciones.getPanelAgregar().getjTpiso().setText("" + piso);
        frame_habitaciones.getPanelAgregar().getjTcapacidad()
                .setText("" + cantidad_personas);
        frame_habitaciones.getPanelAgregar().getjTprecio()
                .setText("" + precio_hab);
        
        
        establecerCombobox(frame_habitaciones.getPanelAgregar().getjCtipoHabi(),
                tipo_hab);
        establecerCombobox(frame_habitaciones.getPanelAgregar()
                .getjCnumeroCamas(),
                "" + num_camas);

    }

    public void establecerCombobox(JComboBox Jcombo, String valor) {

       // JOptionPane.showMessageDialog
       //(null, Jcombo.getItemAt(4) + " algo* " + valor + "****");
        
        for (int i = 0; i < Jcombo.getItemCount(); i++) {

            if (valor.equalsIgnoreCase(Jcombo.getItemAt(i).toString())) {
                Jcombo.setSelectedIndex(i);
            }
        }

    }

    /* public void cargarPeliculasTabla(ArrayList<Pelicula> listadoPelicula) {
        DefaultTableModel defaultCombo;
        defaultCombo = (DefaultTableModel) jTable2.getModel();
        limpiarListadoTabla();
        for (int i = 0; i < listadoPelicula.size(); i++) {
            defaultCombo.addRow(new Object[]{
                listadoPelicula.get(i).getPeliculaId(),
                listadoPelicula.get(i).getTitulo(),
                listadoPelicula.get(i).getAnhoLanzamiento(),
                listadoPelicula.get(i).getLongitud() + " Minutos", 
     
            });
        }

        //Muestra en el campo de texto de la Interfaz el ID cliente Consecutivo
        valor = Integer.parseInt("" + defaultCombo.getValueAt
    //(defaultCombo.getRowCount() - 1, 0)) + 1;
        jTid_peli.setText("" + valor);
        jTid_peli.setEnabled(false);

    }*/
 /* //Cargar datos a la base
     public void CargarListaBase(ArrayList){
        
        //TODA LAS HABITACIONES SON AGREGADAS AL JPANEL 
        //EN DONDE SE MUESTRA LOS DATOS PRINCIPALES DE LAS HABITACIONES
        
        for(int i=0;i<5;i++){
              
        hab.get(i).getId_habitacion();
        hab.get(i).getTipo_habitacion();
        hab.get(i).getPrecio_hab();
        hab.get(i).getEstado();
            
        jPhabitacion jp = new jPhabitacion(02,3.56,"Matrimonial",true);  
        habitaciones.add(jp);
          
       }
        for(int i=0;i<habitaciones.size();i++){          
        jPmensajes.add(habitaciones.get(i));
        
        jPmensajes.revalidate();
        jPmensajes.repaint();}
    }*/

    private void jTbuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTbuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTbuscadorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBbuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPmensajes;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTbuscador;
    // End of variables declaration//GEN-END:variables
}
