/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Jpanel;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author nicol
 */
public class HabitacionAgregarModificarGUI_1 extends javax.swing.JPanel {
    
    /**
     * Creates new form HabitacionAgregarModificarGUI
     */
    String validador;
    
    public HabitacionAgregarModificarGUI_1() {
        initComponents();
        cargarTipoHabitacion();
        cargarNumCamas();
        validador = "guardar";
    }

    public void setValidador(String validador) {
        this.validador = validador;
    }

    public String getValidador() {
        return validador;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBcancelar = new javax.swing.JButton();
        jTprecio = new javax.swing.JTextField();
        jBguardar = new javax.swing.JButton();
        jCnumeroCamas = new javax.swing.JComboBox();
        jTnumeroHabitacion = new javax.swing.JTextField();
        jCtipoHabi = new javax.swing.JComboBox();
        jTcapacidad = new javax.swing.JTextField();
        jTpiso = new javax.swing.JTextField();
        jLfondo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(241, 242, 246));
        setPreferredSize(new java.awt.Dimension(739, 429));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar-sinSeleccion.png"))); // NOI18N
        jBcancelar.setContentAreaFilled(false);
        jBcancelar.setInheritsPopupMenu(true);
        jBcancelar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar-seleccionado.png"))); // NOI18N
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });
        add(jBcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 130, 50));

        jTprecio.setBackground(new java.awt.Color(241, 242, 246));
        jTprecio.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jTprecio.setForeground(new java.awt.Color(153, 153, 153));
        jTprecio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTprecio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTprecioFocusGained(evt);
            }
        });
        jTprecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTprecioKeyTyped(evt);
            }
        });
        add(jTprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 190, 30));

        jBguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar-blanco.png"))); // NOI18N
        jBguardar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jBguardar.setContentAreaFilled(false);
        jBguardar.setInheritsPopupMenu(true);
        jBguardar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar-seleccionado.png"))); // NOI18N
        jBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarActionPerformed(evt);
            }
        });
        add(jBguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, -1, -1));

        jCnumeroCamas.setBackground(new java.awt.Color(241, 242, 246));
        jCnumeroCamas.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jCnumeroCamas.setForeground(new java.awt.Color(153, 153, 153));
        jCnumeroCamas.setBorder(null);
        jCnumeroCamas.setOpaque(false);
        jCnumeroCamas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCnumeroCamasActionPerformed(evt);
            }
        });
        add(jCnumeroCamas, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 120, 30));

        jTnumeroHabitacion.setBackground(new java.awt.Color(241, 242, 246));
        jTnumeroHabitacion.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jTnumeroHabitacion.setForeground(new java.awt.Color(153, 153, 153));
        jTnumeroHabitacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTnumeroHabitacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTnumeroHabitacionFocusGained(evt);
            }
        });
        jTnumeroHabitacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTnumeroHabitacionKeyTyped(evt);
            }
        });
        add(jTnumeroHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 190, 30));

        jCtipoHabi.setBackground(new java.awt.Color(241, 242, 246));
        jCtipoHabi.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jCtipoHabi.setForeground(new java.awt.Color(153, 153, 153));
        jCtipoHabi.setBorder(null);
        jCtipoHabi.setOpaque(false);
        add(jCtipoHabi, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 190, 30));

        jTcapacidad.setBackground(new java.awt.Color(241, 242, 246));
        jTcapacidad.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jTcapacidad.setForeground(new java.awt.Color(153, 153, 153));
        jTcapacidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTcapacidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTcapacidadFocusGained(evt);
            }
        });
        jTcapacidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTcapacidadKeyTyped(evt);
            }
        });
        add(jTcapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 190, 30));

        jTpiso.setBackground(new java.awt.Color(241, 242, 246));
        jTpiso.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jTpiso.setForeground(new java.awt.Color(153, 153, 153));
        jTpiso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTpiso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTpisoFocusGained(evt);
            }
        });
        jTpiso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTpisoKeyTyped(evt);
            }
        });
        add(jTpiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 190, 30));

        jLfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Grupo 24.png"))); // NOI18N
        jLfondo.setPreferredSize(new java.awt.Dimension(739, 429));
        add(jLfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jCnumeroCamasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCnumeroCamasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCnumeroCamasActionPerformed

    private void jBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jBguardarActionPerformed

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jTpisoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTpisoKeyTyped
        // TODO add your handling code here:
        validaNumero(evt.getKeyChar(), evt);
        
    }//GEN-LAST:event_jTpisoKeyTyped

    private void jTpisoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTpisoFocusGained
        // TODO add your handling code here:
        if (jTpiso.getText().equalsIgnoreCase("****")){
            jTpiso.setForeground(Color.BLACK);
            jTpiso.setText("");
        }
        
    }//GEN-LAST:event_jTpisoFocusGained

    private void jTcapacidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTcapacidadFocusGained
        // TODO add your handling code here:
        if (jTcapacidad.getText().equalsIgnoreCase("****")){
            jTcapacidad.setForeground(Color.BLACK);
            jTcapacidad.setText("");
        }
    }//GEN-LAST:event_jTcapacidadFocusGained

    private void jTprecioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTprecioFocusGained
        // TODO add your handling code here:
        if (jTprecio.getText().equalsIgnoreCase("****")){
            jTprecio.setForeground(Color.BLACK);
            jTprecio.setText("");
        }
        
    }//GEN-LAST:event_jTprecioFocusGained

    private void jTnumeroHabitacionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTnumeroHabitacionFocusGained
        // TODO add your handling code here:
        if (jTnumeroHabitacion.getText().equalsIgnoreCase("****")){
            jTnumeroHabitacion.setForeground(Color.BLACK);
            jTnumeroHabitacion.setText("");
        }
        
    }//GEN-LAST:event_jTnumeroHabitacionFocusGained

    private void jTnumeroHabitacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTnumeroHabitacionKeyTyped
        // TODO add your handling code here:
        validaNumero(evt.getKeyChar(), evt);
    }//GEN-LAST:event_jTnumeroHabitacionKeyTyped

    private void jTcapacidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTcapacidadKeyTyped
        // TODO add your handling code here:
        validaNumero(evt.getKeyChar(), evt);
    }//GEN-LAST:event_jTcapacidadKeyTyped

    private void jTprecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTprecioKeyTyped
        // TODO add your handling code here:
        validaNumero(evt.getKeyChar(), evt);
    }//GEN-LAST:event_jTprecioKeyTyped

    /*public void Modificar(int numero_){
        
       //SE BUSCA EN LA BASE DE DATOS EL NÚMERO DE HABITACIÓN Y SE COMPARA
       /* Por hacer*/
   //    int numeroH = Integer.parseInt(jTnumeroHabitacion.getText());
        
     //  if(numero_ == numeroH){
           //LOS DATOS QUE DEVUELVE SE PONE EN LA INTERFAZ
     //  }
        
    //}
    
    
   
    public JButton getjBcancelar() {
        return jBcancelar;
    }

    public JButton getjBguardar() {
        return jBguardar;
    }

    public JTextField getjTcapacidad() {
        return jTcapacidad;
    }

    public JTextField getjTnumeroHabitacion() {
        return jTnumeroHabitacion;
    }

    public JTextField getjTpiso() {
        return jTpiso;
    }

    public JTextField getjTprecio() {
        return jTprecio;
    }

    public JComboBox getjCnumeroCamas() {
        return jCnumeroCamas;
    }

    public JComboBox getjCtipoHabi() {
        return jCtipoHabi;
    }
    
    
    //Mensajes
    public void gestionMensajes(String mensaje, String titulo, int icono) {
        JOptionPane.showMessageDialog(this, mensaje, titulo, icono);
    }
    
    //Metodo para cargar Tipo de habitacion a un combo box
    public void cargarTipoHabitacion (){
        DefaultComboBoxModel model;
        
        String [] arregloTipoHabitacion = new String [5];
        
        arregloTipoHabitacion[0] = "Seleccione...";
        arregloTipoHabitacion[1] = "SIMPLE";
        arregloTipoHabitacion[2] = "DOBLE";
        arregloTipoHabitacion[3] = "MATRIMONIAL";
        arregloTipoHabitacion[4] = "SUITES";
        
        model = new DefaultComboBoxModel (arregloTipoHabitacion);
        
        jCtipoHabi.setModel(model);
    }
    
    //Método para cargar número de camas en un combobox
    public void cargarNumCamas (){
        DefaultComboBoxModel model;
        
        String [] arregloNumeroCamas = new String [4];
        
        arregloNumeroCamas[0] = "Seleccione...";
        arregloNumeroCamas[1] = "1";
        arregloNumeroCamas[2] = "2";
        arregloNumeroCamas[3] = "3";
        
        model = new DefaultComboBoxModel (arregloNumeroCamas);
        
        jCnumeroCamas.setModel(model);
    }
    
    public int validarCampos() {
        int rtdo = 1;
        
        if (jTnumeroHabitacion.getText().equals("") || jTnumeroHabitacion.getText().equals("****")) {

            rtdo = 0;
            mostrarCamposVacios(jTnumeroHabitacion);

        }
        if (jTpiso.getText().equals("") || jTpiso.getText().equals("****")) {

            rtdo = 0;
            mostrarCamposVacios(jTpiso);

        }
        if (jTcapacidad.getText().equals("") || jTcapacidad.getText().equals("****")) {
            
            rtdo = 0;
            mostrarCamposVacios(jTcapacidad);
        }
        if(jTprecio.getText().equals("") || jTprecio.getText().equals("****")) {
                  
            rtdo = 0;
            mostrarCamposVacios(jTprecio);
        }
        if(jCnumeroCamas.getSelectedItem().equals("Seleccione...") ){
          
            rtdo= 0;
            //animacionCombobox();
        }
        
        if(jCtipoHabi.getSelectedItem().equals("Seleccione...")){
          
            rtdo= 0;
            animacionCombobox();
        }       
  
        return rtdo;
    }
    
    public void animacionCombobox(){
        
        Thread obj = new Thread();
        
        try {
            jCtipoHabi.setBackground(Color.blue);
            obj.sleep(3000);
            jCtipoHabi.setBackground(Color.white);
            obj.sleep(3000);
            jCtipoHabi.setBackground(Color.blue);
            obj.sleep(3000);
            jCtipoHabi.setBackground(Color.yellow);
        } catch (InterruptedException ex) {
            Logger.getLogger(HabitacionAgregarModificarGUI_1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    

    public void mostrarCamposVacios(JTextField jt) {
        jt.setForeground(Color.blue);
        jt.setText("****");

    }
    
    public void validaNumero(char c, KeyEvent evt) {
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }
    
    public void setearCampos() {

        jTnumeroHabitacion.setText("");
        jTpiso.setText("");
        jTcapacidad.setText("");
        jTprecio.setText("");
        jCtipoHabi.setSelectedIndex(0);
        jCnumeroCamas.setSelectedIndex(0);
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBguardar;
    private javax.swing.JComboBox jCnumeroCamas;
    private javax.swing.JComboBox jCtipoHabi;
    private javax.swing.JLabel jLfondo;
    private javax.swing.JTextField jTcapacidad;
    private javax.swing.JTextField jTnumeroHabitacion;
    private javax.swing.JTextField jTpiso;
    private javax.swing.JTextField jTprecio;
    // End of variables declaration//GEN-END:variables
}

