/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Jpanel;

import Controladores.ControladorCliente;
import Modelo.Cliente;
import Vistas.Jframe.ClienteRecepcionista;

/**
 *
 * @author nicol
 */
public class jPclienteRecepcionista extends javax.swing.JPanel {

    /**
     * Creates new form jPclienteRecepcionista
     */
    
    private Cliente datosCliente; // datos cliente
    private int id;
    private String nombre,apellido, telefono, correo;
    ClienteRecepcionista frame_cliente_rec;
    
    public jPclienteRecepcionista(Cliente datosCli, ClienteRecepcionista cr){
        
        this.frame_cliente_rec = cr;
        this.datosCliente = datosCli;
        this.id = datosCliente.getID();
        this.nombre = datosCliente.getNombre();
        this.apellido = datosCliente.getApellido();
        this.telefono = datosCliente.getTelefono();
        this.correo = datosCliente.getCorreo();
        initComponents();
        
        jLnumeroCliente.setText(String.valueOf(id));
        jLnombreCliente.setText(nombre);
        jLApellidoCli.setText(apellido);
        jLTelefonoCli.setText(telefono);
        jLcorreoCli.setText(correo);
    }
    
         public void cambiarPanel() {
        frame_cliente_rec.FormularioModificar(
                ControladorCliente.listClients(id).get(0));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLnumeroCliente = new javax.swing.JLabel();
        jLnombreCliente = new javax.swing.JLabel();
        jLApellidoCli = new javax.swing.JLabel();
        jLTelefonoCli = new javax.swing.JLabel();
        jLcorreoCli = new javax.swing.JLabel();
        jBeditar = new javax.swing.JLabel();
        jBtodoPanel = new javax.swing.JButton();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLnumeroCliente.setBackground(new java.awt.Color(112, 112, 112));
        jLnumeroCliente.setFont(new java.awt.Font("Decker", 0, 10)); // NOI18N
        jLnumeroCliente.setForeground(new java.awt.Color(112, 112, 112));
        jLnumeroCliente.setText("Número");
        add(jLnumeroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 28, 60, 13));

        jLnombreCliente.setBackground(new java.awt.Color(112, 112, 112));
        jLnombreCliente.setFont(new java.awt.Font("Decker", 0, 10)); // NOI18N
        jLnombreCliente.setForeground(new java.awt.Color(112, 112, 112));
        jLnombreCliente.setText("Nombre");
        add(jLnombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 80, 13));

        jLApellidoCli.setBackground(new java.awt.Color(112, 112, 112));
        jLApellidoCli.setFont(new java.awt.Font("Decker", 0, 10)); // NOI18N
        jLApellidoCli.setForeground(new java.awt.Color(112, 112, 112));
        jLApellidoCli.setText("Apellido");
        add(jLApellidoCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 100, -1));

        jLTelefonoCli.setFont(new java.awt.Font("Decker", 0, 10)); // NOI18N
        jLTelefonoCli.setForeground(new java.awt.Color(112, 112, 112));
        jLTelefonoCli.setText("Telefono");
        add(jLTelefonoCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 60, -1));

        jLcorreoCli.setBackground(new java.awt.Color(112, 112, 112));
        jLcorreoCli.setFont(new java.awt.Font("Decker", 0, 10)); // NOI18N
        jLcorreoCli.setForeground(new java.awt.Color(112, 112, 112));
        jLcorreoCli.setText("correo");
        add(jLcorreoCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 30, -1));

        jBeditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconEditar.png"))); // NOI18N
        jBeditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBeditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBeditarMouseClicked(evt);
            }
        });
        add(jBeditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 16, 16));

        jBtodoPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CliSinSele.png"))); // NOI18N
        jBtodoPanel.setBorderPainted(false);
        jBtodoPanel.setContentAreaFilled(false);
        jBtodoPanel.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CliSele.png"))); // NOI18N
        jBtodoPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtodoPanelActionPerformed(evt);
            }
        });
        add(jBtodoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 819, 68));
    }// </editor-fold>//GEN-END:initComponents

    private void jBtodoPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtodoPanelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtodoPanelActionPerformed

    private void jBeditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBeditarMouseClicked
        // TODO add your handling code here:
        cambiarPanel();
        
    }//GEN-LAST:event_jBeditarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBeditar;
    private javax.swing.JButton jBtodoPanel;
    private javax.swing.JLabel jLApellidoCli;
    private javax.swing.JLabel jLTelefonoCli;
    private javax.swing.JLabel jLcorreoCli;
    private javax.swing.JLabel jLnombreCliente;
    private javax.swing.JLabel jLnumeroCliente;
    // End of variables declaration//GEN-END:variables
}
