/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Jpanel;

import javax.swing.JOptionPane;

/**
 *
 * @author nicol
 */
public class jPhabitacion extends javax.swing.JPanel {

    
    private int numero;
    private double precio;
    private String tipo;
    private boolean estado;
    private String eleccion;
    private int result;
    
    /**
     * Creates new form jPhabitacion
     */

    public jPhabitacion(int numero_,double precio_, String tipo_,boolean estado_) {
        this.numero = numero_;
        this.precio = precio_;
        this.tipo = tipo_;
        this.estado = estado_;       
        initComponents();
        
        jLnumero.setText(String.valueOf(numero_));
        jLprecio.setText(String.valueOf(precio_));
        jLtipo.setText(tipo_);
        
        if(estado_ = true)
          jLestado.setText("Disponible");
        else
            jLestado.setText("Ocupado");
               
    }

    public jPhabitacion(){
        
    }
    public jPhabitacion(String eleccion_) {
       this.eleccion = eleccion_;
       setEleccion(eleccion_);
              
}
 
          
    public void setEleccion(String val){
        eleccion = val;
    }
    
    public void borrarPanel(){
  
        if(eleccion == "eliminar"){
          new HabitacionAgregarModificarGUI().setVisible(true);
            
   }else{
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null,"Desea continuar?","Eliminar",dialog);
        
                if(result == 0)
                {                     
                setVisible(false);
                }
       }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLnumero = new javax.swing.JLabel();
        jLtipo = new javax.swing.JLabel();
        jLprecio = new javax.swing.JLabel();
        jLestado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setOpaque(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLnumero.setFont(new java.awt.Font("Decker", 0, 11)); // NOI18N
        add(jLnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 31, 70, 10));

        jLtipo.setFont(new java.awt.Font("Decker", 0, 11)); // NOI18N
        add(jLtipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 48, 90, 10));

        jLprecio.setFont(new java.awt.Font("Decker", 0, 11)); // NOI18N
        add(jLprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 63, 70, 10));
        add(jLestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 80, 70, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Habitación-jpanel.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 210, 130));
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        
        borrarPanel();
        
        
        
        
    }//GEN-LAST:event_formMouseClicked
/**/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLestado;
    private javax.swing.JLabel jLnumero;
    private javax.swing.JLabel jLprecio;
    private javax.swing.JLabel jLtipo;
    // End of variables declaration//GEN-END:variables
}
