/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Jpanel;

/**
 *
 * @author nicol
 */
public class jPserviciosRecepcionista2 extends javax.swing.JPanel {

    private String nombre;
    private double precio;
    private int cantidad;
    /**
     * Creates new form jPserviciosRecepcionista2
     */
    public jPserviciosRecepcionista2(String nombre_,double precio_, int cantidad_) {
        initComponents();
        jLnombre.setText(nombre_);
        jLprecio.setText(String.valueOf(precio_));
        jLcantidad.setText(String.valueOf(cantidad_));   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLcantidad = new javax.swing.JLabel();
        jLnombre = new javax.swing.JLabel();
        jLprecio = new javax.swing.JLabel();
        jBeliminar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLcantidad.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jLcantidad.setForeground(new java.awt.Color(112, 112, 112));
        jLcantidad.setText("02");
        add(jLcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 7, -1, -1));

        jLnombre.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jLnombre.setForeground(new java.awt.Color(112, 112, 112));
        jLnombre.setText("Chocolate");
        add(jLnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 8, -1, -1));

        jLprecio.setFont(new java.awt.Font("Decker", 0, 12)); // NOI18N
        jLprecio.setForeground(new java.awt.Color(112, 112, 112));
        jLprecio.setText("55");
        add(jLprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 8, -1, -1));

        jBeliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconEliminar.png"))); // NOI18N
        jBeliminar.setBorder(null);
        jBeliminar.setContentAreaFilled(false);
        jBeliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeliminarActionPerformed(evt);
            }
        });
        add(jBeliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 7, 20, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 27, 200, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jBeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeliminarActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jBeliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBeliminar;
    private javax.swing.JLabel jLcantidad;
    private javax.swing.JLabel jLnombre;
    private javax.swing.JLabel jLprecio;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
