/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Jpanel;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author nicol
 */
public class panelAgregarServicio extends javax.swing.JPanel {

    /**
     * Creates new form ServiciosAgregarModificar
     */
    String validadorBoton; //valida si se requiere hacer una actuslizacion o una ingreso del un registro
    

    public panelAgregarServicio() {
        validadorBoton = "guardar";
        initComponents();
    }

    public void setValidadorBoton(String validador) {
        this.validadorBoton = validador;
    }

    public String getValidador() {
        return validadorBoton;
    }

  

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTprecio = new javax.swing.JTextField();
        jTNombre = new javax.swing.JTextField();
        jTcantidad = new javax.swing.JTextField();
        jLnombre = new javax.swing.JLabel();
        jLcantidad = new javax.swing.JLabel();
        jLprecio = new javax.swing.JLabel();
        jBcancelar = new javax.swing.JButton();
        jBguardar = new javax.swing.JButton();
        jLfondo = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTprecio.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jTprecio.setForeground(new java.awt.Color(153, 153, 153));
        jTprecio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTprecio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTprecioFocusGained(evt);
            }
        });
        jTprecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTprecioKeyTyped(evt);
            }
        });
        add(jTprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 322, 276, 25));

        jTNombre.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jTNombre.setForeground(new java.awt.Color(153, 153, 153));
        jTNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTNombreFocusGained(evt);
            }
        });
        jTNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTNombreKeyTyped(evt);
            }
        });
        add(jTNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 184, 276, 25));

        jTcantidad.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jTcantidad.setForeground(new java.awt.Color(153, 153, 153));
        jTcantidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTcantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTcantidadFocusGained(evt);
            }
        });
        jTcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTcantidadKeyTyped(evt);
            }
        });
        add(jTcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 250, 276, 25));

        jLnombre.setFont(new java.awt.Font("Decker", 0, 16)); // NOI18N
        jLnombre.setForeground(new java.awt.Color(191, 191, 191));
        jLnombre.setText("Nombre");
        add(jLnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 152, -1, -1));

        jLcantidad.setFont(new java.awt.Font("Decker", 0, 16)); // NOI18N
        jLcantidad.setForeground(new java.awt.Color(191, 191, 191));
        jLcantidad.setText("Cantidad");
        add(jLcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 222, -1, -1));

        jLprecio.setFont(new java.awt.Font("Decker", 0, 16)); // NOI18N
        jLprecio.setForeground(new java.awt.Color(191, 191, 191));
        jLprecio.setText("Precio");
        add(jLprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 291, -1, -1));

        jBcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar-sinSeleccion.png"))); // NOI18N
        jBcancelar.setBorder(null);
        jBcancelar.setBorderPainted(false);
        jBcancelar.setContentAreaFilled(false);
        jBcancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBcancelar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar-seleccionado.png"))); // NOI18N
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });
        add(jBcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 374, 130, 50));

        jBguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar-SinSele.png"))); // NOI18N
        jBguardar.setBorder(null);
        jBguardar.setContentAreaFilled(false);
        jBguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBguardar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuardarSele.png"))); // NOI18N
        jBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarActionPerformed(evt);
            }
        });
        add(jBguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 374, -1, -1));

        jLfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MarcoServicio.png"))); // NOI18N
        jLfondo.setOpaque(true);
        jLfondo.setPreferredSize(new java.awt.Dimension(739, 429));
        add(jLfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 68, 575, 397));
    }// </editor-fold>//GEN-END:initComponents

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBguardarActionPerformed

    private void jTNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTNombreFocusGained
        // TODO add your handling code here:
        if (jTNombre.getText().equalsIgnoreCase("****")) {
            jTNombre.setForeground(Color.BLACK);
            jTNombre.setText("");
        }
    }//GEN-LAST:event_jTNombreFocusGained

    private void jTcantidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTcantidadFocusGained
        // TODO add your handling code here:
        if (jTcantidad.getText().equalsIgnoreCase("****")) {
            jTcantidad.setForeground(Color.BLACK);
            jTcantidad.setText("");
        }
    }//GEN-LAST:event_jTcantidadFocusGained

    private void jTprecioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTprecioFocusGained
        // TODO add your handling code here:
        if (jTprecio.getText().equalsIgnoreCase("****")) {
            jTprecio.setForeground(Color.BLACK);
            jTprecio.setText("");
        }
    }//GEN-LAST:event_jTprecioFocusGained

    private void jTNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTNombreKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTNombreKeyTyped

    private void jTcantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTcantidadKeyTyped
        // TODO add your handling code here:
        validaNumero(evt.getKeyChar(), evt);
    }//GEN-LAST:event_jTcantidadKeyTyped

    private void jTprecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTprecioKeyTyped
        // TODO add your handling code here:
        validaNumero(evt.getKeyChar(), evt);
    }//GEN-LAST:event_jTprecioKeyTyped

    
    public void setearCampos() {
        jTNombre.setText("");
        jTcantidad.setText("");
        jTprecio.setText("");

    }
    
     
    public int validarCampos() {
        int rtdo = 1;

        if (jTNombre.getText().equals("") || jTNombre.getText().equals("****"))
        {

            rtdo = 0;
            mostrarCamposVacios(jTNombre);

        }
        if (jTcantidad.getText().equals("") || jTcantidad.getText().equals("****"))
        {
            rtdo = 0;

            mostrarCamposVacios(jTcantidad);
        }
        if(jTprecio.getText().equals("") || jTprecio.getText().equals("****"))
        {
            rtdo = 0;

            mostrarCamposVacios(jTprecio);
        }
        return rtdo;
    }
    
    public void mostrarCamposVacios(JTextField jt) {
        jt.setForeground(Color.blue);
        jt.setText("****");
    }
    
    public void validaNumero(char c, KeyEvent evt) {
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }
    public JButton getjBcancelar() {
        return jBcancelar;
    }

    public JTextField getjTNombre() {
        return jTNombre;
    }

    public JTextField getjTcantidad() {
        return jTcantidad;
    }

    public JTextField getjTprecio() {
        return jTprecio;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBguardar;
    private javax.swing.JLabel jLcantidad;
    private javax.swing.JLabel jLfondo;
    private javax.swing.JLabel jLnombre;
    private javax.swing.JLabel jLprecio;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTcantidad;
    private javax.swing.JTextField jTprecio;
    // End of variables declaration//GEN-END:variables
}
