/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Jpanel;

/**
 *
 * @author nicol
 */
public class RealizarReservaGUI extends javax.swing.JPanel {

    /**
     * Creates new form RealizarReservaGUI
     */
    public RealizarReservaGUI() {
        initComponents();
        agregarHabitaciones();
    }

    private void agregarHabitaciones(){
        
        jPcontenido.removeAll();
        for (int i=0;i<9;i++){
        jPhabitacionCheckIn jp = new jPhabitacionCheckIn(05,"Simple",53.000,02);
        jPcontenido.add(jp);
          
       }
        jPcontenido.revalidate();
        jPcontenido.repaint();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBcancelar = new javax.swing.JButton();
        jBguardar = new javax.swing.JButton();
        jTidCliente = new javax.swing.JTextField();
        jTfechaIngreso = new javax.swing.JTextField();
        jTfechaRserva = new javax.swing.JTextField();
        jTidHabitacion = new javax.swing.JTextField();
        jTfechaSalida = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPcontenido = new javax.swing.JPanel();
        jBbuscar = new javax.swing.JButton();
        jLformulario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar-sinSeleccion.png"))); // NOI18N
        jBcancelar.setBorder(null);
        jBcancelar.setBorderPainted(false);
        jBcancelar.setContentAreaFilled(false);
        jBcancelar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar-seleccionado.png"))); // NOI18N
        add(jBcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 395, 125, 40));

        jBguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar-blanco.png"))); // NOI18N
        jBguardar.setBorder(null);
        jBguardar.setContentAreaFilled(false);
        jBguardar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar-seleccionado.png"))); // NOI18N
        add(jBguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(706, 395, 125, 40));

        jTidCliente.setFont(new java.awt.Font("Decker", 0, 16)); // NOI18N
        jTidCliente.setForeground(new java.awt.Color(191, 191, 191));
        jTidCliente.setText("Cliente");
        jTidCliente.setBorder(null);
        jTidCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTidClienteActionPerformed(evt);
            }
        });
        add(jTidCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 152, 240, 23));

        jTfechaIngreso.setFont(new java.awt.Font("Decker", 0, 16)); // NOI18N
        jTfechaIngreso.setForeground(new java.awt.Color(191, 191, 191));
        jTfechaIngreso.setText("Fecha de ingreso");
        jTfechaIngreso.setBorder(null);
        add(jTfechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 345, 240, 23));

        jTfechaRserva.setFont(new java.awt.Font("Decker", 0, 16)); // NOI18N
        jTfechaRserva.setForeground(new java.awt.Color(191, 191, 191));
        jTfechaRserva.setText("Fecha de reserva");
        jTfechaRserva.setBorder(null);
        add(jTfechaRserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 301, 240, 23));

        jTidHabitacion.setFont(new java.awt.Font("Decker", 0, 16)); // NOI18N
        jTidHabitacion.setForeground(new java.awt.Color(191, 191, 191));
        jTidHabitacion.setText("  Número de habitación");
        jTidHabitacion.setBorder(null);
        add(jTidHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 203, 274, 23));

        jTfechaSalida.setFont(new java.awt.Font("Decker", 0, 16)); // NOI18N
        jTfechaSalida.setForeground(new java.awt.Color(191, 191, 191));
        jTfechaSalida.setText("Fecha salida");
        jTfechaSalida.setBorder(null);
        add(jTfechaSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 252, 240, 23));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setOpaque(false);

        jPcontenido.setBackground(new java.awt.Color(255, 255, 255));
        jPcontenido.setLayout(new java.awt.GridLayout(0, 1, 0, 1));
        jScrollPane1.setViewportView(jPcontenido);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 119, 300, 360));

        jBbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar-azul.png"))); // NOI18N
        jBbuscar.setBorder(null);
        jBbuscar.setContentAreaFilled(false);
        jBbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jBbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(837, 153, 24, 24));

        jLformulario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MarcoReserva.png"))); // NOI18N
        add(jLformulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 85, 575, 397));

        jLabel1.setBackground(new java.awt.Color(112, 112, 112));
        jLabel1.setFont(new java.awt.Font("Decker", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(112, 112, 112));
        jLabel1.setText("Número    Tipo     Precio   Capacidad");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 89, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(204, 204, 204));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Simple" }));
        jComboBox1.setBorder(null);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 37, 122, 20));

        jLabel2.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(165, 165, 165));
        jLabel2.setText("Habitaciones :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 37, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTidClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTidClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTidClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBbuscar;
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBguardar;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLformulario;
    private javax.swing.JPanel jPcontenido;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTfechaIngreso;
    private javax.swing.JTextField jTfechaRserva;
    private javax.swing.JTextField jTfechaSalida;
    private javax.swing.JTextField jTidCliente;
    private javax.swing.JTextField jTidHabitacion;
    // End of variables declaration//GEN-END:variables
}
