/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Jpanel;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author nicol
 */
public class RegistrarSalidaGUI extends javax.swing.JPanel {

    private int idCliente;
    private int idEmpleado;
    private int idHabitacion;
    private String fechaIngreso;
    private String fechaSalida;
    private double precio;
    private ArrayList<String> servicios;
    
    /**
     * Creates new form RegistrarSalidaGUI
     */
    public RegistrarSalidaGUI() {
        initComponents();
        
    }
    
    public RegistrarSalidaGUI(int idCliente_,int idEmpleado_, int idHabitacion_,
    String fIngreso, String fSalida,double precio_){
     
        servicios = new  ArrayList<>();
    this.idCliente = idCliente_;
    this.idEmpleado = idEmpleado_;
    this.idHabitacion = idHabitacion_;
    this.fechaIngreso = fIngreso;
    this.fechaSalida = fSalida;
    this.precio = precio_;
    
//    agregarDatosFactura();
           
    }
    /*
    private void agregarDatosFactura(){
      
      //DATOS A MOSTRAR EN LA FACTURA 
       
      jLcliente.setText(String.valueOf(idCliente));
      jLempleado.setText(String.valueOf(idEmpleado));
      jLhabitacion.setText(String.valueOf(idHabitacion));    
      jLfechaIngreso.setText(fechaIngreso);
      jLfechaSalida.setText(fechaSalida);
      jLprecio.setText(String.valueOf(precio));
      
      
      //LISTA DE SERVICIOS 

   /*

    DefaultListModel modelo = new DefaultListModel();
      for(int i=0;i<9;i++){    
        modelo.addElement(i);         
       }
       jListServicios.setModel(modelo); 
    }

      */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTbuscador = new javax.swing.JTextField();
        jLcliente = new javax.swing.JLabel();
        jLempleado = new javax.swing.JLabel();
        jLhabitacion = new javax.swing.JLabel();
        jLfechaIngreso = new javax.swing.JLabel();
        jLfechaSalida = new javax.swing.JLabel();
        jLprecio = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListServicios = new javax.swing.JList<>();
        jLfactura = new javax.swing.JLabel();
        jBcancelar = new javax.swing.JButton();
        jBcheckOut = new javax.swing.JButton();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTbuscador.setFont(new java.awt.Font("Decker", 0, 15)); // NOI18N
        jTbuscador.setForeground(new java.awt.Color(191, 191, 191));
        jTbuscador.setText("Buscar reserva por ID de cliente");
        jTbuscador.setBorder(null);
        add(jTbuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 47, -1, -1));

        jLcliente.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jLcliente.setForeground(new java.awt.Color(112, 112, 112));
        jLcliente.setText("123456789");
        add(jLcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 153, -1, -1));

        jLempleado.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jLempleado.setForeground(new java.awt.Color(112, 112, 112));
        jLempleado.setText("123456789");
        add(jLempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 178, -1, -1));

        jLhabitacion.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jLhabitacion.setForeground(new java.awt.Color(112, 112, 112));
        jLhabitacion.setText("123456789");
        add(jLhabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 203, -1, -1));

        jLfechaIngreso.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jLfechaIngreso.setForeground(new java.awt.Color(112, 112, 112));
        jLfechaIngreso.setText("123456789");
        add(jLfechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 227, -1, -1));

        jLfechaSalida.setFont(new java.awt.Font("Decker", 0, 13)); // NOI18N
        jLfechaSalida.setForeground(new java.awt.Color(112, 112, 112));
        jLfechaSalida.setText("123456789");
        add(jLfechaSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 250, -1, -1));

        jLprecio.setFont(new java.awt.Font("Decker", 1, 20)); // NOI18N
        jLprecio.setForeground(new java.awt.Color(112, 112, 112));
        jLprecio.setText("600.000");
        add(jLprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 315, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar-azul.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 44, 24, 24));

        jScrollPane2.setBorder(null);
        jScrollPane2.setForeground(new java.awt.Color(112, 112, 112));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setFont(new java.awt.Font("Decker", 0, 9)); // NOI18N

        jScrollPane2.setViewportView(jListServicios);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 373, 260, 45));

        jLfactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Factura.png"))); // NOI18N
        add(jLfactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 88, -1, -1));

        jBcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar-sinSeleccion.png"))); // NOI18N
        jBcancelar.setContentAreaFilled(false);
        jBcancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBcancelar.setInheritsPopupMenu(true);
        jBcancelar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar-seleccionado.png"))); // NOI18N
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });
        add(jBcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 445, 130, 50));

        jBcheckOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonCheckOutSinSele.png"))); // NOI18N
        jBcheckOut.setBorder(null);
        jBcheckOut.setContentAreaFilled(false);
        jBcheckOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBcheckOut.setInheritsPopupMenu(true);
        jBcheckOut.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonCheckOutSele.png"))); // NOI18N
        jBcheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcheckOutActionPerformed(evt);
            }
        });
        add(jBcheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 445, 140, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jBcheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcheckOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBcheckOutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBcheckOut;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLcliente;
    private javax.swing.JLabel jLempleado;
    private javax.swing.JLabel jLfactura;
    private javax.swing.JLabel jLfechaIngreso;
    private javax.swing.JLabel jLfechaSalida;
    private javax.swing.JLabel jLhabitacion;
    private javax.swing.JList<String> jListServicios;
    private javax.swing.JLabel jLprecio;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTbuscador;
    // End of variables declaration//GEN-END:variables
}
