/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Jframe;

import Controladores.ControladorCliente;
import Modelo.Cliente;
import Vistas.Jpanel.ClienteListaGUI;
import Vistas.Jpanel.ClientesAgregarModificarGUI;
import Vistas.Jpanel.ClientesRegistradosGUI;

/**
 * @author nicol
 */
public class ClienteRecepcionista extends javax.swing.JPanel {

    ClientesAgregarModificarGUI formulario;
    ClientesRegistradosGUI panelListar;
    ControladorCliente controlador;

    public ClienteRecepcionista() {

        initComponents();
        formulario = new ClientesAgregarModificarGUI(this);
        seleccionarPrimero(formulario);

    }

    public void AgregarCliente(Cliente c) {
        controlador.addClient(c);
    }

    public void panelListarCliente() {
        panelListar = new ClientesRegistradosGUI(this);
        jBregistrar.setSelected(false);
        jBlistaClientes.setSelected(true);
        jPcontenedor.setVisible(false);
        jPcontenedor.setVisible(true);
        jPcontenedor.removeAll();
        jPcontenedor.add(panelListar);
        jPcontenedor.revalidate();
        jPcontenedor.repaint();
    }
    
    public void FormularioModificar(Cliente llenar ){
        
        jBlistaClientes.setSelected(false);
        jBregistrar.setSelected(true); 
        jPcontenedor.removeAll();
        formulario.llenarValores(llenar);
        jPcontenedor.add(formulario);   
        jPcontenedor.revalidate();
        jPcontenedor.repaint();
        jPcontenedor.setVisible(true);
 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBlistaClientes = new javax.swing.JButton();
        jBregistrar = new javax.swing.JButton();
        jPcontenedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(239, 239, 239));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBlistaClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonRegistradosSinSele.png"))); // NOI18N
        jBlistaClientes.setBorder(null);
        jBlistaClientes.setBorderPainted(false);
        jBlistaClientes.setContentAreaFilled(false);
        jBlistaClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBlistaClientes.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonRegistradosSele.png"))); // NOI18N
        jBlistaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlistaClientesActionPerformed(evt);
            }
        });
        add(jBlistaClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 115, 117, 32));

        jBregistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonRegistrarSinsele.png"))); // NOI18N
        jBregistrar.setBorder(null);
        jBregistrar.setBorderPainted(false);
        jBregistrar.setContentAreaFilled(false);
        jBregistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBregistrar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonRegistrarSele.png"))); // NOI18N
        jBregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBregistrarActionPerformed(evt);
            }
        });
        add(jBregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 115, 55, 30));

        jPcontenedor.setBackground(new java.awt.Color(255, 255, 255));
        jPcontenedor.setLayout(new java.awt.BorderLayout());
        add(jPcontenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 146, 1021, 534));

        jLabel1.setFont(new java.awt.Font("Decker", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(112, 112, 112));
        jLabel1.setText("Cliente");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jBlistaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlistaClientesActionPerformed
        // TODO add your handling code here:
        panelListarCliente();
        formulario.limpiarCampos();
    }//GEN-LAST:event_jBlistaClientesActionPerformed

    public void seleccionarPrimero(ClientesAgregarModificarGUI formulario) {

        jBlistaClientes.setSelected(false);
        jBregistrar.setSelected(true);
        jPcontenedor.removeAll();
        jPcontenedor.add(formulario);
        jPcontenedor.revalidate();
        jPcontenedor.repaint();
        jPcontenedor.setVisible(true);
    }


    private void jBregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBregistrarActionPerformed

        jPcontenedor.removeAll();
        seleccionarPrimero(formulario);
    }//GEN-LAST:event_jBregistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBlistaClientes;
    private javax.swing.JButton jBregistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPcontenedor;
    // End of variables declaration//GEN-END:variables
}
