/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Jframe;

import Controladores.ControladorEmpleado;
import Modelo.Empleado;
import Vistas.Jpanel.EmpleadoFormulario;
import Vistas.Jpanel.EmpleadoPanelListar;
import Vistas.Jpanel.HabitacionAgregarModificarGUI;
import Vistas.Jpanel.HabitacionListaGUI;
import Vistas.Jpanel.jPhabitacion;
import javax.swing.JOptionPane;

/**
 *
 * @author nicol
 */
public class Empleados extends javax.swing.JPanel {

    /**
     * Creates new form EmpleadoGUI
     */
    
    /*public Empleados() {
        initComponents();
        seleccionarPrimero();
        
    }*/
    EmpleadoFormulario formulario;
    EmpleadoPanelListar panelListar;
    ControladorEmpleado controlador;
    
    public Empleados()
    {
        initComponents();
        formulario = new EmpleadoFormulario(this);
        
        seleccionarPrimero(formulario);
    }
    
    public void setControladorEmpleado(ControladorEmpleado s){
        
        this.controlador = s;
        
    }
    
    public ControladorEmpleado getControladorEmpleado()
    {
        return controlador;
    }
    
    
    public void AgregarEmpleado(Empleado c)
    {
        controlador.grabarEmpleado(c);
    }
    
    
    public void FormularioModificar(Empleado llenar){
        //jBeliminar.setSelected(false);
        jBmodificar.setSelected(true);
        jBagregar.setSelected(false); 
        jPcontenedor.removeAll();
        formulario.llenarValores(llenar);
        formulario.setValidar("modificar");
        jPcontenedor.add(formulario);
        jPcontenedor.revalidate();
        jPcontenedor.repaint();
        jPcontenedor.setVisible(true);
    }
    
    
    public void btnModificar()
    {
        panelListar = new EmpleadoPanelListar(this);
        jBagregar.setSelected(false);
//        jBeliminar.setSelected(false);
        jBmodificar.setSelected(true);
        jPcontenedor.setVisible(false);
        jPcontenedor.setVisible(true);
        jPcontenedor.removeAll();
        
        jPcontenedor.add(panelListar);
        
        jPcontenedor.revalidate();
        jPcontenedor.repaint();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBmodificar = new javax.swing.JButton();
        jBagregar = new javax.swing.JButton();
        jPcontenedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(239, 239, 239));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonModificarSinSele.png"))); // NOI18N
        jBmodificar.setBorder(null);
        jBmodificar.setBorderPainted(false);
        jBmodificar.setContentAreaFilled(false);
        jBmodificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBmodificar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonModificarSele.png"))); // NOI18N
        jBmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmodificarActionPerformed(evt);
            }
        });
        add(jBmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 115, 56, 30));

        jBagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonAgregarSinSele.png"))); // NOI18N
        jBagregar.setBorder(null);
        jBagregar.setBorderPainted(false);
        jBagregar.setContentAreaFilled(false);
        jBagregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBagregar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonAgregarSele.png"))); // NOI18N
        jBagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBagregarActionPerformed(evt);
            }
        });
        add(jBagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 115, 49, 30));

        jPcontenedor.setBackground(new java.awt.Color(255, 255, 255));
        jPcontenedor.setLayout(new java.awt.BorderLayout());
        add(jPcontenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 146, 1021, 534));

        jLabel1.setFont(new java.awt.Font("Decker", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(112, 112, 112));
        jLabel1.setText("Empleado");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jBmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmodificarActionPerformed
        // TODO add your handling code here:
       btnModificar();
    }//GEN-LAST:event_jBmodificarActionPerformed

    public void seleccionarPrimero(EmpleadoFormulario formulario){
        formulario.limpiarCampos();
        formulario.setValidar("agregar");
//        jBeliminar.setSelected(false);
        jBmodificar.setSelected(false);
        jBagregar.setSelected(true); 
        
        jPcontenedor.removeAll();
        jPcontenedor.add(formulario);
        jPcontenedor.revalidate();
        jPcontenedor.repaint();
        jPcontenedor.setVisible(true);
    }
     
    private void jBagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBagregarActionPerformed
        // TODO add your handling code here:
        
         jPcontenedor.removeAll();
         seleccionarPrimero(formulario);

    }//GEN-LAST:event_jBagregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBagregar;
    private javax.swing.JButton jBmodificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPcontenedor;
    // End of variables declaration//GEN-END:variables
}
