/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Jframe;

import Vistas.Jpanel.HabitacionAgregarModificarGUI;
import java.awt.Toolkit;

/**
 *
 * @author nicol
 */
public class Habitacion extends javax.swing.JFrame {

    /**
     * Creates new form Habitación
     */
    public Habitacion() {
        super( "Administrador");
        initComponents();       
        setResizable(false);
        this.setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("/imagenes/Logo.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPcontenedor = new javax.swing.JPanel();
        jBhabitaciones = new javax.swing.JButton();
        jBclientes = new javax.swing.JButton();
        jBempleados = new javax.swing.JButton();
        jBcerrarSesion = new javax.swing.JButton();
        jBagregar = new javax.swing.JButton();
        jBeliminar = new javax.swing.JButton();
        jBmodificar = new javax.swing.JButton();
        jLmenuCrud = new javax.swing.JLabel();
        jLfondoGris = new javax.swing.JLabel();
        jLfondoAzul = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(241, 242, 246));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPcontenedor.setOpaque(false);
        jPcontenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPcontenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 730, 420));

        jBhabitaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SinSelección-habi.png"))); // NOI18N
        jBhabitaciones.setBorder(null);
        jBhabitaciones.setBorderPainted(false);
        jBhabitaciones.setContentAreaFilled(false);
        jBhabitaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBhabitaciones.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBhabitaciones.setMaximumSize(new java.awt.Dimension(0, 0));
        jBhabitaciones.setMinimumSize(new java.awt.Dimension(0, 0));
        jBhabitaciones.setPreferredSize(new java.awt.Dimension(0, 129));
        jBhabitaciones.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Seleccion-habi.png"))); // NOI18N
        jBhabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBhabitacionesActionPerformed(evt);
            }
        });
        jPanel1.add(jBhabitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 150, 260, -1));

        jBclientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sinseleccion-cli.png"))); // NOI18N
        jBclientes.setBorder(null);
        jBclientes.setBorderPainted(false);
        jBclientes.setContentAreaFilled(false);
        jBclientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBclientes.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBclientes.setMaximumSize(new java.awt.Dimension(0, 0));
        jBclientes.setMinimumSize(new java.awt.Dimension(0, 0));
        jBclientes.setPreferredSize(new java.awt.Dimension(0, 129));
        jBclientes.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Seleccion-cli.png"))); // NOI18N
        jBclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBclientesActionPerformed(evt);
            }
        });
        jPanel1.add(jBclientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 250, 260, -1));

        jBempleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SinSeleccionar-emp.png"))); // NOI18N
        jBempleados.setBorder(null);
        jBempleados.setBorderPainted(false);
        jBempleados.setContentAreaFilled(false);
        jBempleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBempleados.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBempleados.setMaximumSize(new java.awt.Dimension(0, 0));
        jBempleados.setMinimumSize(new java.awt.Dimension(0, 0));
        jBempleados.setPreferredSize(new java.awt.Dimension(0, 129));
        jBempleados.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Seleccion-empl_1.png"))); // NOI18N
        jBempleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBempleadosActionPerformed(evt);
            }
        });
        jPanel1.add(jBempleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 355, 260, -1));

        jBcerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonSalida.png"))); // NOI18N
        jBcerrarSesion.setBorder(null);
        jBcerrarSesion.setBorderPainted(false);
        jBcerrarSesion.setContentAreaFilled(false);
        jBcerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBcerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcerrarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(jBcerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 590, -1, -1));

        jBagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Seleccion-agregarGris.png"))); // NOI18N
        jBagregar.setBorder(null);
        jBagregar.setBorderPainted(false);
        jBagregar.setContentAreaFilled(false);
        jBagregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBagregar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Seleccion-agregar.png"))); // NOI18N
        jBagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBagregarActionPerformed(evt);
            }
        });
        jPanel1.add(jBagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 97, -1, -1));

        jBeliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Seleccion-eliminarGris.png"))); // NOI18N
        jBeliminar.setBorder(null);
        jBeliminar.setBorderPainted(false);
        jBeliminar.setContentAreaFilled(false);
        jBeliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBeliminar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/seleccion-eliminar.png"))); // NOI18N
        jPanel1.add(jBeliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 97, 100, 40));

        jBmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Seleccion-modificarGris.png"))); // NOI18N
        jBmodificar.setBorder(null);
        jBmodificar.setBorderPainted(false);
        jBmodificar.setContentAreaFilled(false);
        jBmodificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBmodificar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Seleccion-modificar.png"))); // NOI18N
        jPanel1.add(jBmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 97, 90, -1));

        jLmenuCrud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu-crud.png"))); // NOI18N
        jPanel1.add(jLmenuCrud, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, -1, -1));

        jLfondoGris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo-principal.png"))); // NOI18N
        jPanel1.add(jLfondoGris, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 0, 900, 690));

        jLfondoAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/panel-azul.png"))); // NOI18N
        jPanel1.add(jLfondoAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 290, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBhabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBhabitacionesActionPerformed
        // TODO add your handling code here:
        jBhabitaciones.setEnabled(true);
    }//GEN-LAST:event_jBhabitacionesActionPerformed

    private void jBclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBclientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBclientesActionPerformed

    private void jBempleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBempleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBempleadosActionPerformed

    private void jBagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBagregarActionPerformed
        // TODO add your handling code here:
      
      /*  HabitacionAgregarModificarGUI panelAM = new HabitacionAgregarModificarGUI();       
        
        jPcontenedor.setSize(735,429);
        jPcontenedor.removeAll();
        jPcontenedor.add(panelAM);
        jPcontenedor.revalidate();
        jPcontenedor.repaint();*/
      
    }//GEN-LAST:event_jBagregarActionPerformed

    private void jBcerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcerrarSesionActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_jBcerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Habitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Habitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Habitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Habitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Habitacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBagregar;
    private javax.swing.JButton jBcerrarSesion;
    private javax.swing.JButton jBclientes;
    private javax.swing.JButton jBeliminar;
    private javax.swing.JButton jBempleados;
    private javax.swing.JButton jBhabitaciones;
    private javax.swing.JButton jBmodificar;
    private javax.swing.JLabel jLfondoAzul;
    private javax.swing.JLabel jLfondoGris;
    private javax.swing.JLabel jLmenuCrud;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPcontenedor;
    // End of variables declaration//GEN-END:variables
}
