/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Jframe;

/**
 *
 * @author nicol
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        
        initComponents();
        jPRegistro.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBinicia = new javax.swing.JButton();
        jBregistrar = new javax.swing.JButton();
        Menu = new javax.swing.JLabel();
        jLlogo = new javax.swing.JLabel();
        jPRegistro = new javax.swing.JPanel();
        jTcedula = new javax.swing.JTextField();
        jTcedula1 = new javax.swing.JTextField();
        jTtelefono = new javax.swing.JTextField();
        jTcedula3 = new javax.swing.JTextField();
        jTnombre = new javax.swing.JTextField();
        jTcedula6 = new javax.swing.JTextField();
        jBrgistrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLfondo1 = new javax.swing.JLabel();
        jPiniciarSesion = new javax.swing.JPanel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTusername1 = new javax.swing.JTextField();
        jLinput = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(69, 170, 242));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBinicia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iniciar-sinselect.png"))); // NOI18N
        jBinicia.setBorder(null);
        jBinicia.setContentAreaFilled(false);
        jBinicia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBinicia.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Iniciar-select.png"))); // NOI18N
        jBinicia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBiniciaActionPerformed(evt);
            }
        });
        jPanel1.add(jBinicia, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 253, -1, -1));

        jBregistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registrar-sinselect.png"))); // NOI18N
        jBregistrar.setBorder(null);
        jBregistrar.setContentAreaFilled(false);
        jBregistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBregistrar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registrar-select.png"))); // NOI18N
        jBregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBregistrarActionPerformed(evt);
            }
        });
        jPanel1.add(jBregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 253, -1, -1));

        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu-Inicio.png"))); // NOI18N
        jPanel1.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, -1, 60));

        jLlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        jPanel1.add(jLlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 59, -1, -1));

        jPRegistro.setBackground(new java.awt.Color(69, 170, 242));
        jPRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTcedula.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jTcedula.setForeground(new java.awt.Color(112, 112, 112));
        jTcedula.setText("Dirección");
        jTcedula.setBorder(null);
        jTcedula.setOpaque(false);
        jTcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcedulaActionPerformed(evt);
            }
        });
        jPRegistro.add(jTcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 190, 30));

        jTcedula1.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jTcedula1.setForeground(new java.awt.Color(112, 112, 112));
        jTcedula1.setText("Cédula");
        jTcedula1.setBorder(null);
        jTcedula1.setOpaque(false);
        jTcedula1.setSelectedTextColor(new java.awt.Color(69, 170, 242));
        jTcedula1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcedula1ActionPerformed(evt);
            }
        });
        jPRegistro.add(jTcedula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 190, 30));

        jTtelefono.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jTtelefono.setForeground(new java.awt.Color(112, 112, 112));
        jTtelefono.setText("Télefono");
        jTtelefono.setBorder(null);
        jTtelefono.setOpaque(false);
        jTtelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTtelefonoActionPerformed(evt);
            }
        });
        jPRegistro.add(jTtelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 190, 30));

        jTcedula3.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jTcedula3.setForeground(new java.awt.Color(112, 112, 112));
        jTcedula3.setText("Correo");
        jTcedula3.setBorder(null);
        jTcedula3.setOpaque(false);
        jTcedula3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcedula3ActionPerformed(evt);
            }
        });
        jPRegistro.add(jTcedula3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 190, 30));

        jTnombre.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jTnombre.setForeground(new java.awt.Color(112, 112, 112));
        jTnombre.setText("Nombre");
        jTnombre.setBorder(null);
        jTnombre.setOpaque(false);
        jTnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnombreActionPerformed(evt);
            }
        });
        jPRegistro.add(jTnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 190, 30));

        jTcedula6.setFont(new java.awt.Font("Decker", 0, 14)); // NOI18N
        jTcedula6.setForeground(new java.awt.Color(112, 112, 112));
        jTcedula6.setText("Cargo");
        jTcedula6.setBorder(null);
        jTcedula6.setOpaque(false);
        jTcedula6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcedula6ActionPerformed(evt);
            }
        });
        jPRegistro.add(jTcedula6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 190, 30));

        jBrgistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registro-select.png"))); // NOI18N
        jBrgistrar.setBorder(null);
        jBrgistrar.setContentAreaFilled(false);
        jBrgistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPRegistro.add(jBrgistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inputText.png"))); // NOI18N
        jPRegistro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inputText.png"))); // NOI18N
        jPRegistro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inputText.png"))); // NOI18N
        jPRegistro.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inputText.png"))); // NOI18N
        jPRegistro.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inputText.png"))); // NOI18N
        jPRegistro.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inputText.png"))); // NOI18N
        jPRegistro.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));

        jLfondo1.setBackground(new java.awt.Color(69, 170, 242));
        jLfondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo-registro.png"))); // NOI18N
        jLfondo1.setAlignmentX(327.0F);
        jLfondo1.setAlignmentY(208.0F);
        jLfondo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPRegistro.add(jLfondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 660, -1));

        jPanel1.add(jPRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 208, 680, 440));

        jPiniciarSesion.setBackground(new java.awt.Color(69, 170, 242));
        jPiniciarSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPasswordField1.setText("Contraseña");
        jPasswordField1.setBorder(null);
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPiniciarSesion.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 260, 20));

        jTusername1.setText("Usuario");
        jTusername1.setBorder(null);
        jTusername1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTusername1ActionPerformed(evt);
            }
        });
        jPiniciarSesion.add(jTusername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 270, 20));

        jLinput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Input.png"))); // NOI18N
        jPiniciarSesion.add(jLinput, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IniciarSesión-select.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPiniciarSesion.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        jLfondo.setBackground(new java.awt.Color(69, 170, 242));
        jLfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo-login.png"))); // NOI18N
        jLfondo.setAlignmentX(327.0F);
        jLfondo.setAlignmentY(208.0F);
        jLfondo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPiniciarSesion.add(jLfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPiniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 208, -1, 370));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1118, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTusername1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTusername1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTusername1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jBiniciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBiniciaActionPerformed
        // TODO add your handling code here:
        jPRegistro.setVisible(false);
        jPiniciarSesion.setVisible(true);
    }//GEN-LAST:event_jBiniciaActionPerformed

    private void jBregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBregistrarActionPerformed
        // TODO add your handling code here:
        jPiniciarSesion.setVisible(false);
        jPRegistro.setVisible(true);
       
    }//GEN-LAST:event_jBregistrarActionPerformed

    private void jTcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTcedulaActionPerformed

    private void jTcedula1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcedula1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTcedula1ActionPerformed

    private void jTtelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTtelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTtelefonoActionPerformed

    private void jTcedula3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcedula3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTcedula3ActionPerformed

    private void jTnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnombreActionPerformed

    private void jTcedula6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcedula6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTcedula6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Menu;
    private javax.swing.JButton jBinicia;
    private javax.swing.JButton jBregistrar;
    private javax.swing.JButton jBrgistrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLfondo;
    private javax.swing.JLabel jLfondo1;
    private javax.swing.JLabel jLinput;
    private javax.swing.JLabel jLlogo;
    private javax.swing.JPanel jPRegistro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPanel jPiniciarSesion;
    private javax.swing.JTextField jTcedula;
    private javax.swing.JTextField jTcedula1;
    private javax.swing.JTextField jTcedula3;
    private javax.swing.JTextField jTcedula6;
    private javax.swing.JTextField jTnombre;
    private javax.swing.JTextField jTtelefono;
    private javax.swing.JTextField jTusername1;
    // End of variables declaration//GEN-END:variables
}
