/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Jframe;
import Controladores.ControladorEmpleado;
import Controladores.ControllerServicios;
import Modelo.RoomServicesDAO;
import Controladores.ControllerHabitacion;
import Modelo.HabitacionDAO;
import Vistas.Jpanel.HabitacionAgregarModificarGUI;
import Vistas.Jpanel.HabitacionListaGUI;
import Vistas.Jpanel.jPhabitacion;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import Vistas.Jpanel.EmpleadoFormulario;
import Vistas.Jpanel.EmpleadoPanelListar;
import java.awt.Toolkit;
/**
 *
 * @author nicol
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Habitación
     */
    Habitaciones Jframehabitaciones;
    Services JframeServices;
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        seleccionarPrimero();
        setResizable(false);
        
        setIconImage(Toolkit.getDefaultToolkit().
        getImage(this.getClass().getResource("/imagenes/Logo.png")));
       
       HabitacionDAO modelohabitacion = new HabitacionDAO();
       ControllerHabitacion controladorHabitacion 
               = new ControllerHabitacion(Jframehabitaciones, modelohabitacion); 
        Jframehabitaciones.setControladorHabitacion(controladorHabitacion);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBhabitaciones = new javax.swing.JButton();
        jBempleados = new javax.swing.JButton();
        jBclientes = new javax.swing.JButton();
        jBservicios = new javax.swing.JButton();
        jBcerrarSesion = new javax.swing.JButton();
        jPcontenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));
        setMinimumSize(new java.awt.Dimension(1118, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(72, 159, 229));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBhabitaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/HabitacionBotonSinSele.png"))); // NOI18N
        jBhabitaciones.setBorder(null);
        jBhabitaciones.setBorderPainted(false);
        jBhabitaciones.setContentAreaFilled(false);
        jBhabitaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBhabitaciones.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBhabitaciones.setMaximumSize(new java.awt.Dimension(0, 0));
        jBhabitaciones.setMinimumSize(new java.awt.Dimension(0, 0));
        jBhabitaciones.setPreferredSize(new java.awt.Dimension(0, 129));
        jBhabitaciones.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/HabitacionBotonSele.png"))); // NOI18N
        jBhabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBhabitacionesActionPerformed(evt);
            }
        });
        jPanel1.add(jBhabitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 121, 97, 57));

        jBempleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmpleadosBotonSinSele.png"))); // NOI18N
        jBempleados.setBorder(null);
        jBempleados.setBorderPainted(false);
        jBempleados.setContentAreaFilled(false);
        jBempleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBempleados.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBempleados.setMaximumSize(new java.awt.Dimension(0, 0));
        jBempleados.setMinimumSize(new java.awt.Dimension(0, 0));
        jBempleados.setPreferredSize(new java.awt.Dimension(0, 129));
        jBempleados.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EmpleadosBotonSele.png"))); // NOI18N
        jBempleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBempleadosActionPerformed(evt);
            }
        });
        jPanel1.add(jBempleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 301, 97, 57));

        jBclientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CheckInBoton.png"))); // NOI18N
        jBclientes.setBorder(null);
        jBclientes.setBorderPainted(false);
        jBclientes.setContentAreaFilled(false);
        jBclientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBclientes.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBclientes.setMaximumSize(new java.awt.Dimension(0, 0));
        jBclientes.setMinimumSize(new java.awt.Dimension(0, 0));
        jBclientes.setPreferredSize(new java.awt.Dimension(0, 129));
        jBclientes.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CheckInBotonSele.png"))); // NOI18N
        jBclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBclientesActionPerformed(evt);
            }
        });
        jPanel1.add(jBclientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 218, 97, 57));

        jBservicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/serviciosBoton.png"))); // NOI18N
        jBservicios.setBorder(null);
        jBservicios.setBorderPainted(false);
        jBservicios.setContentAreaFilled(false);
        jBservicios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBservicios.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBservicios.setMaximumSize(new java.awt.Dimension(0, 0));
        jBservicios.setMinimumSize(new java.awt.Dimension(0, 0));
        jBservicios.setPreferredSize(new java.awt.Dimension(0, 129));
        jBservicios.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/serviciosBotonSele.png"))); // NOI18N
        jBservicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBserviciosActionPerformed(evt);
            }
        });
        jPanel1.add(jBservicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 396, 97, 57));

        jBcerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonSalida.png"))); // NOI18N
        jBcerrarSesion.setBorder(null);
        jBcerrarSesion.setBorderPainted(false);
        jBcerrarSesion.setContentAreaFilled(false);
        jBcerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBcerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcerrarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(jBcerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 610, 30, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 97, 680));

        jPcontenedor.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPcontenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 0, 1021, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBhabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBhabitacionesActionPerformed
        // TODO add your handling code here:
        /* jBservicios.setSelected(false);
        jBempleados.setSelected(false);
        jBclientes.setSelected(false);
        jBhabitaciones.setSelected(true);
        Habitaciones habi = new Habitaciones() ;
        jPcontenedor.removeAll();
        jPcontenedor.add(habi);
        jPcontenedor.revalidate();
        jPcontenedor.repaint();
        jPcontenedor.setVisible(true);*/
        seleccionarPrimero();
        HabitacionDAO modelohabitacion = new HabitacionDAO();
        ControllerHabitacion controladorHabitacion
        = new ControllerHabitacion(Jframehabitaciones, modelohabitacion);
        Jframehabitaciones.setControladorHabitacion(controladorHabitacion);
    }//GEN-LAST:event_jBhabitacionesActionPerformed

    private void jBempleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBempleadosActionPerformed
        // TODO add your handling code here:
        jBservicios.setSelected(false);
        jBclientes.setSelected(false);
        jBhabitaciones.setSelected(false);
        jBempleados.setSelected(true);

        jPcontenedor.setVisible(false);
        ControladorEmpleado controladorEmp = new ControladorEmpleado();
        Empleados emp = new Empleados();
        emp.setControladorEmpleado(controladorEmp);
        jPcontenedor.removeAll();
        jPcontenedor.add(emp);
        jPcontenedor.revalidate();
        jPcontenedor.repaint();
        jPcontenedor.setVisible(true);
    }//GEN-LAST:event_jBempleadosActionPerformed

    private void jBclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBclientesActionPerformed
        // TODO add your handling code here:
        jBservicios.setSelected(false);
        jBempleados.setSelected(false);
        jBhabitaciones.setSelected(false);
        jBclientes.setSelected(true);

        jPcontenedor.setVisible(false);
        Clientes cli = new Clientes() ;
        jPcontenedor.removeAll();
        jPcontenedor.add(cli);
        jPcontenedor.revalidate();
        jPcontenedor.repaint();
        jPcontenedor.setVisible(true);
    }//GEN-LAST:event_jBclientesActionPerformed

    private void jBserviciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBserviciosActionPerformed
        // TODO add your handling code here:

        jBempleados.setSelected(false);
        jBclientes.setSelected(false);
        jBhabitaciones.setSelected(false);
        jBservicios.setSelected(true);

        jPcontenedor.setVisible(false);

        RoomServicesDAO modelo = new RoomServicesDAO();
        JframeServices = new Services();
        jPcontenedor.removeAll();
        jPcontenedor.add(JframeServices);
        jPcontenedor.revalidate();
        jPcontenedor.repaint();
        jPcontenedor.setVisible(true);
    }//GEN-LAST:event_jBserviciosActionPerformed

    private void jBcerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcerrarSesionActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_jBcerrarSesionActionPerformed

    public void seleccionarPrimero(){
       jBservicios.setSelected(false);
        jBempleados.setSelected(false);
        jBclientes.setSelected(false);
        jBhabitaciones.setSelected(true);
       Jframehabitaciones = new Habitaciones() ;
        jPcontenedor.removeAll();
        jPcontenedor.add(Jframehabitaciones);
        jPcontenedor.revalidate();
        jPcontenedor.repaint();
        jPcontenedor.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcerrarSesion;
    private javax.swing.JButton jBclientes;
    private javax.swing.JButton jBempleados;
    private javax.swing.JButton jBhabitaciones;
    private javax.swing.JButton jBservicios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPcontenedor;
    // End of variables declaration//GEN-END:variables
}
