/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Jframe;

import Modelo.Habitacion;
import Servicios.Fecha;
import Vistas.Jpanel.ListaReservasGUI;
import Vistas.Jpanel.RealizarReservaGUI;
import java.sql.Timestamp;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author nicol
 */
public class Reservas extends javax.swing.JPanel {

    /**
     * Creates new form Reserva
     */
    
    ListaReservasGUI pListareserva;
    RealizarReservaGUI pRealizarReserva;
    
    public Reservas() {
        initComponents();
        seleccionarPrimero();
    }
    
    public void seleccionarPrimero(){
        jBlistaReserva.setSelected(false); 
        jBrrealizarReserva.setSelected(true);
                
        pRealizarReserva = new RealizarReservaGUI();
        jPcontenedor.removeAll();
        jPcontenedor.add(pRealizarReserva);
        jPcontenedor.revalidate();
        jPcontenedor.repaint();
        jPcontenedor.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPcontenedor = new javax.swing.JPanel();
        jBrrealizarReserva = new javax.swing.JButton();
        jBlistaReserva = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(239, 239, 239));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPcontenedor.setBackground(new java.awt.Color(255, 255, 255));
        jPcontenedor.setVerifyInputWhenFocusTarget(false);
        jPcontenedor.setLayout(new java.awt.BorderLayout());
        add(jPcontenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 146, 1021, 534));

        jBrrealizarReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/RealizarReserva.png"))); // NOI18N
        jBrrealizarReserva.setBorder(null);
        jBrrealizarReserva.setContentAreaFilled(false);
        jBrrealizarReserva.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/RealizarReservaSele.png"))); // NOI18N
        jBrrealizarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrrealizarReservaActionPerformed(evt);
            }
        });
        add(jBrrealizarReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 115, -1, -1));

        jBlistaReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ListaReserva.png"))); // NOI18N
        jBlistaReserva.setBorder(null);
        jBlistaReserva.setContentAreaFilled(false);
        jBlistaReserva.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ListaReservaSele.png"))); // NOI18N
        jBlistaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlistaReservaActionPerformed(evt);
            }
        });
        add(jBlistaReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 115, -1, -1));

        jLabel1.setFont(new java.awt.Font("Decker", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(112, 112, 112));
        jLabel1.setText("Reserva");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jBrrealizarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrrealizarReservaActionPerformed
        // TODO add your handling code here:

        jPcontenedor.removeAll();
        seleccionarPrimero();
    }//GEN-LAST:event_jBrrealizarReservaActionPerformed

    private void jBlistaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlistaReservaActionPerformed
        // TODO add your handling code here:        
        jBrrealizarReserva.setSelected(false);
        jBlistaReserva.setSelected(true); 
           
        jPcontenedor.setVisible(false);
        jPcontenedor.setVisible(true);
        jPcontenedor.removeAll();
        pListareserva = new ListaReservasGUI();

        jPcontenedor.add(pListareserva);
        jPcontenedor.revalidate();
        jPcontenedor.repaint();
        jPcontenedor.setVisible(true);
        
    }//GEN-LAST:event_jBlistaReservaActionPerformed

    
    public void CargarHabitaciones(ArrayList<Habitacion> lista){
        
        pRealizarReserva.agregarHabitaciones(lista);
        
    }

    public ListaReservasGUI getpListareserva() {
        return pListareserva;
    }

    public RealizarReservaGUI getpRealizarReserva() {
        return pRealizarReserva;
    }
    
    
    
    
    public String getTextjTfechaIngreso() {
        return pRealizarReserva.getjTfechaIngreso().getText().trim();
    }

    public String getTextjTfechaRserva() {
        return pRealizarReserva.getjTfechaRserva().getText().trim();
    }

    public String getTextjTfechaSalida() {
        return pRealizarReserva.getjTfechaSalida().getText().trim();
    }

    public String getTextjTidCliente() {
        return pRealizarReserva.getjTidCliente().getText().trim();
    }

    public String getTextjTidHabitacion() {
        return pRealizarReserva.getjTidHabitacion().getText().trim();
        
    }
    
    public Timestamp getFechaIngreso(){
        return Fecha.cambiarFecha(pRealizarReserva.getJdFechaIngreso().getDate());
    }
    
    public Timestamp getFechaSalida(){
        return Fecha.cambiarFecha(pRealizarReserva.getJdFechaSalida().getDate());
    }

    
    public void gestionMensajes(String mensaje, String titulo, int icono) {
        JOptionPane.showMessageDialog(this, mensaje, titulo, icono);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBlistaReserva;
    private javax.swing.JButton jBrrealizarReserva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPcontenedor;
    // End of variables declaration//GEN-END:variables
}
