/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Jframe;

import Vistas.Jpanel.ListaReservasGUI;
import Vistas.Jpanel.RealizarReservaGUI;

/**
 *
 * @author nicol
 */
public class Reserva extends javax.swing.JPanel {

    /**
     * Creates new form Reserva
     */
    public Reserva() {
        initComponents();
        seleccionarPrimero();
    }
    
    public void seleccionarPrimero(){
        jBlistaReserva.setSelected(false); 
        jBrrealizarReserva.setSelected(true);
                
        RealizarReservaGUI reser_ = new RealizarReservaGUI();
        jPcontenedor.removeAll();
        jPcontenedor.add(reser_);
        jPcontenedor.revalidate();
        jPcontenedor.repaint();
        jPcontenedor.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPcontenedor = new javax.swing.JPanel();
        jBrrealizarReserva = new javax.swing.JButton();
        jBlistaReserva = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(239, 239, 239));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPcontenedor.setBackground(new java.awt.Color(255, 255, 255));
        jPcontenedor.setVerifyInputWhenFocusTarget(false);
        jPcontenedor.setLayout(new java.awt.BorderLayout());
        add(jPcontenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 146, 1021, 534));

        jBrrealizarReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/RealizarReserva.png"))); // NOI18N
        jBrrealizarReserva.setBorder(null);
        jBrrealizarReserva.setContentAreaFilled(false);
        jBrrealizarReserva.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/RealizarReservaSele.png"))); // NOI18N
        jBrrealizarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrrealizarReservaActionPerformed(evt);
            }
        });
        add(jBrrealizarReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 115, -1, -1));

        jBlistaReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ListaReserva.png"))); // NOI18N
        jBlistaReserva.setBorder(null);
        jBlistaReserva.setContentAreaFilled(false);
        jBlistaReserva.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ListaReservaSele.png"))); // NOI18N
        jBlistaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlistaReservaActionPerformed(evt);
            }
        });
        add(jBlistaReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 115, -1, -1));

        jLabel1.setFont(new java.awt.Font("Decker", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(112, 112, 112));
        jLabel1.setText("Reserva");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jBrrealizarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrrealizarReservaActionPerformed
        // TODO add your handling code here:

        jPcontenedor.removeAll();
        seleccionarPrimero();
    }//GEN-LAST:event_jBrrealizarReservaActionPerformed

    private void jBlistaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlistaReservaActionPerformed
        // TODO add your handling code here:        
        jBrrealizarReserva.setSelected(false);
        jBlistaReserva.setSelected(true); 
           
        jPcontenedor.setVisible(false);
        jPcontenedor.setVisible(true);
        jPcontenedor.removeAll();
        ListaReservasGUI reserva = new ListaReservasGUI();

        jPcontenedor.add(reserva);
        jPcontenedor.revalidate();
        jPcontenedor.repaint();
        jPcontenedor.setVisible(true);
        
    }//GEN-LAST:event_jBlistaReservaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBlistaReserva;
    private javax.swing.JButton jBrrealizarReserva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPcontenedor;
    // End of variables declaration//GEN-END:variables
}
