/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Jframe;

import Vistas.Jpanel.AgregarServicioRecepGUI;

/**
 *
 * @author nicol
 */
public class ServiciosRecepcionista extends javax.swing.JPanel {

    /**
     * Creates new form ServiciosRecep
     */
    public ServiciosRecepcionista() {
        initComponents();
        seleccionar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPcontenedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBagregarServicio = new javax.swing.JButton();

        setBackground(new java.awt.Color(239, 239, 239));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPcontenedor.setBackground(new java.awt.Color(255, 255, 255));
        jPcontenedor.setVerifyInputWhenFocusTarget(false);
        jPcontenedor.setLayout(new java.awt.BorderLayout());
        add(jPcontenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 146, 1021, 534));

        jLabel1.setFont(new java.awt.Font("Decker", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(112, 112, 112));
        jLabel1.setText("Servicio");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jBagregarServicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonAregarServicioSinSele.png"))); // NOI18N
        jBagregarServicio.setBorder(null);
        jBagregarServicio.setContentAreaFilled(false);
        jBagregarServicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBagregarServicio.setSelected(true);
        jBagregarServicio.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonAregarServicio.png"))); // NOI18N
        add(jBagregarServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 115, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionar(){
        jBagregarServicio.setSelected(true);
        AgregarServicioRecepGUI servi= new  AgregarServicioRecepGUI();
        jPcontenedor.removeAll();
        jPcontenedor.add(servi);
        jPcontenedor.revalidate();
        jPcontenedor.repaint();
        jPcontenedor.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBagregarServicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPcontenedor;
    // End of variables declaration//GEN-END:variables
}
